////////////////////////////////////////////////////////////////////
//
// D:\dev\cs15_hp\src\common\xlast_csgo\csgo.spa.h
//
// Auto-generated on Friday, 06 July 2012 at 13:42:04
// Xbox LIVE Game Config project version 1.0.417.0
// SPA Compiler version 1.0.0.0
//
////////////////////////////////////////////////////////////////////

#ifndef __COUNTER_STRIKE__GO_SPA_H__
#define __COUNTER_STRIKE__GO_SPA_H__

#ifdef __cplusplus
extern "C" {
#endif

//
// Title info
//

#define TITLEID_COUNTER_STRIKE__GO                  0x5841125A

//
// Context ids
//
// These values are passed as the dwContextId to XUserSetContext.
//

#define CONTEXT_CSS_LEVEL                           1
#define CONTEXT_GAME_STATE                          3
#define CONTEXT_CSS_GAME_MODE                       5
#define CONTEXT_CSS_TEAM                            10
#define CONTEXT_CSS_PRIVACY                         14
#define CONTEXT_CSS_GAME_TYPE                       16
#define CONTEXT_CSS_MAP_GROUP                       17

//
// Context values
//
// These values are passed as the dwContextValue to XUserSetContext.
//

// Values for CONTEXT_CSS_LEVEL

#define CONTEXT_CSS_LEVEL_ITALY                     0
#define CONTEXT_CSS_LEVEL_OFFICE                    1
#define CONTEXT_CSS_LEVEL_AZTEC                     2
#define CONTEXT_CSS_LEVEL_DUST                      3
#define CONTEXT_CSS_LEVEL_DUST2                     4
#define CONTEXT_CSS_LEVEL_INFERNO                   5
#define CONTEXT_CSS_LEVEL_NUKE                      6
#define CONTEXT_CSS_LEVEL_BAGGAGE                   7
#define CONTEXT_CSS_LEVEL_SHOOTS                    8
#define CONTEXT_CSS_LEVEL_LAKE                      9
#define CONTEXT_CSS_LEVEL_BANK                      10
#define CONTEXT_CSS_LEVEL_SAFEHOUSE                 11
#define CONTEXT_CSS_LEVEL_SUGARCANE                 12
#define CONTEXT_CSS_LEVEL_STMARC                    13
#define CONTEXT_CSS_LEVEL_SHORTTRAIN                14
#define CONTEXT_CSS_LEVEL_TRAIN                     15
#define CONTEXT_CSS_LEVEL_TRAINING                  16

// Values for CONTEXT_GAME_STATE

#define CONTEXT_GAME_STATE_IN_MENUS                 0
#define CONTEXT_GAME_STATE_SINGLE_PLAYER            1
#define CONTEXT_GAME_STATE_MULTIPLAYER              2

// Values for CONTEXT_CSS_GAME_MODE

#define CONTEXT_CSS_GAME_MODE_CASUAL                0
#define CONTEXT_CSS_GAME_MODE_COMPETITIVE           1
#define CONTEXT_CSS_GAME_MODE_FREESTYLE             2
#define CONTEXT_CSS_GAME_MODE_GUNGAMEPROGRESSIVE    3
#define CONTEXT_CSS_GAME_MODE_GUNGAMEBOMB           4

// Values for CONTEXT_CSS_TEAM

#define CONTEXT_CSS_TEAM_CT                         0
#define CONTEXT_CSS_TEAM_T                          1
#define CONTEXT_CSS_TEAM_SPECTATOR                  2

// Values for CONTEXT_CSS_PRIVACY

#define CONTEXT_CSS_PRIVACY_PUBLIC                  0
#define CONTEXT_CSS_PRIVACY_FRIENDS                 1
#define CONTEXT_CSS_PRIVACY_INVITE_ONLY             2

// Values for CONTEXT_CSS_GAME_TYPE

#define CONTEXT_CSS_GAME_TYPE_CLASSIC               0
#define CONTEXT_CSS_GAME_TYPE_GUNGAME               1

// Values for CONTEXT_CSS_MAP_GROUP

#define CONTEXT_CSS_MAP_GROUP_BOMB_MG               0
#define CONTEXT_CSS_MAP_GROUP_HOSTAGE_MG            1
#define CONTEXT_CSS_MAP_GROUP_DEMOLITION_MG         2
#define CONTEXT_CSS_MAP_GROUP_ARMSRACE_MG           3
#define CONTEXT_CSS_MAP_GROUP_AZTEC_MG              4
#define CONTEXT_CSS_MAP_GROUP_BAGGAGE_MG            5
#define CONTEXT_CSS_MAP_GROUP_BANK_MG               6
#define CONTEXT_CSS_MAP_GROUP_DUST_MG               7
#define CONTEXT_CSS_MAP_GROUP_DUST2_MG              8
#define CONTEXT_CSS_MAP_GROUP_INFERNO_MG            9
#define CONTEXT_CSS_MAP_GROUP_ITALY_MG              10
#define CONTEXT_CSS_MAP_GROUP_LAKE_MG               11
#define CONTEXT_CSS_MAP_GROUP_NUKE_MG               12
#define CONTEXT_CSS_MAP_GROUP_OFFICE_MG             13
#define CONTEXT_CSS_MAP_GROUP_SAFEHOUSE_MG          14
#define CONTEXT_CSS_MAP_GROUP_SHOOTS_MG             15
#define CONTEXT_CSS_MAP_GROUP_SHORTTRAIN_MG         16
#define CONTEXT_CSS_MAP_GROUP_STMARC_MG             17
#define CONTEXT_CSS_MAP_GROUP_SUGARCANE_MG          18
#define CONTEXT_CSS_MAP_GROUP_TRAIN_MG              19
#define CONTEXT_CSS_MAP_GROUP_TRAINING_MG           20

// Values for X_CONTEXT_PRESENCE

#define CONTEXT_PRESENCE_IDLE                       0
#define CONTEXT_PRESENCE_MAINMENU                   1
#define CONTEXT_PRESENCE_MULTIPLAYER                2
#define CONTEXT_PRESENCE_MULTIPLAYER_NO_SLOTS       3
#define CONTEXT_PRESENCE_MULTIPLAYER_PRIVATE        4
#define CONTEXT_PRESENCE_SINGLEPLAYER               5
#define CONTEXT_PRESENCE_LOBBY                      6

// Values for X_CONTEXT_GAME_MODE

#define CONTEXT_GAME_MODE_CSS_GAME_MODE_MULTIPLAYER 0

//
// Property ids
//
// These values are passed as the dwPropertyId value to XUserSetProperty
// and as the dwPropertyId value in the XUSER_PROPERTY structure.
//

#define PROPERTY_CSS_AGGREGATE_EXPERIENCE           0x10000003
#define PROPERTY_CSS_AGGREGATE_SKILL0               0x10000004
#define PROPERTY_CSS_AGGREGATE_SKILL1               0x10000005
#define PROPERTY_CSS_AGGREGATE_SKILL2               0x10000006
#define PROPERTY_CSS_AGGREGATE_SKILL3               0x10000007
#define PROPERTY_CSS_AGGREGATE_SKILL4               0x10000008
#define PROPERTY_CSS_MATCH_VERSION                  0x1000000B
#define PROPERTY_CSS_OPEN_SLOTS                     0x1000000C
#define PROPERTY_CSS_SEARCH_EXP_MAX                 0x10000016
#define PROPERTY_CSS_SEARCH_EXP_MIN                 0x10000017
#define PROPERTY_CSS_SEARCH_SKILL0_MAX              0x10000018
#define PROPERTY_CSS_SEARCH_SKILL0_MIN              0x10000019
#define PROPERTY_CSS_SEARCH_SKILL1_MAX              0x1000001A
#define PROPERTY_CSS_SEARCH_SKILL1_MIN              0x1000001B
#define PROPERTY_CSS_SEARCH_SKILL2_MAX              0x1000001C
#define PROPERTY_CSS_SEARCH_SKILL2_MIN              0x1000001D
#define PROPERTY_CSS_SEARCH_SKILL3_MAX              0x1000001E
#define PROPERTY_CSS_SEARCH_SKILL3_MIN              0x1000001F
#define PROPERTY_CSS_SEARCH_SKILL4_MAX              0x10000020
#define PROPERTY_CSS_SEARCH_SKILL4_MIN              0x10000021
#define PROPERTY_CSS_GAME_MODE_AS_NUMBER            0x10000026
#define PROPERTY_CSS_LB_CS_AVERAGE_KILLS_PER_ROUND  0x10000041
#define PROPERTY_CSS_LB_CS_AVERAGE_DEATHS_PER_ROUND 0x10000042
#define PROPERTY_CSS_LB_CS_AVERAGE_DAMAGE_PER_ROUND 0x10000043
#define PROPERTY_CSS_LB_CS_MVP_AWARDS_MONTH         0x10000044
#define PROPERTY_CSS_LB_KD_KD_ACTUAL                0x10000046
#define PROPERTY_CSS_LB_KD_HEADSHOT_PERCENT         0x10000047
#define PROPERTY_CSS_LB_KD_HITS_PERCENT             0x10000048
#define PROPERTY_CSS_LB_KD_KILLS                    0x10000049
#define PROPERTY_CSS_LB_CS_TOTAL_ROUNDS_PLAYED      0x1000004B
#define PROPERTY_CSS_LB_CS_TOTAL_KILLS              0x1000004C
#define PROPERTY_CSS_LB_CS_TOTAL_DEATHS             0x1000004D
#define PROPERTY_CSS_LB_CS_TOTAL_DAMAGE             0x1000004E
#define PROPERTY_CSS_LB_CS_TOTAL_CONTRIB_SCORE      0x1000004F
#define PROPERTY_CSS_LB_WINS_WINS                   0x10000051
#define PROPERTY_CSS_LB_WINS_LOSSES                 0x10000052
#define PROPERTY_CSS_LB_WINS_WIN_PERCENT_AS_CT      0x10000053
#define PROPERTY_CSS_LB_WINS_WIN_PERCENT_AS_T       0x10000054
#define PROPERTY_CSS_LB_WINS_WIN_PERCENT            0x10000055
#define PROPERTY_CSS_LB_WINS_WIN_AS_CT              0x10000056
#define PROPERTY_CSS_LB_WINS_WIN_AS_T               0x10000057
#define PROPERTY_CSS_LB_STARS_BOMBS_PLANTED         0x10000059
#define PROPERTY_CSS_LB_STARS_BOMBS_DETONATED       0x1000005A
#define PROPERTY_CSS_LB_STARS_BOMBS_DEFUSED         0x1000005B
#define PROPERTY_CSS_LB_STARS_HOSTAGES_RESCUED      0x1000005C
#define PROPERTY_CSS_LB_GP_TIME_PLAYED              0x1000005E
#define PROPERTY_CSS_LB_GP_PLAYED_CT_PERCENT        0x1000005F
#define PROPERTY_CSS_LB_GP_PLAYED_T_PERCENT         0x10000060
#define PROPERTY_CSS_LB_GP_TOTAL_MEDALS             0x10000061
#define PROPERTY_CSS_LB_GP_TIME_OFFLINE_CASUAL      0x10000062
#define PROPERTY_CSS_LB_GP_TIME_OFFLINE_COMPETITIVE 0x10000063
#define PROPERTY_CSS_LB_GP_TIME_ONLINE_CASUAL       0x10000064
#define PROPERTY_CSS_LB_GP_TIME_ONLINE_COMPETITIVE  0x10000065
#define PROPERTY_CSS_LB_GP_TIME_ONLINE_PRIVATE      0x10000066
#define PROPERTY_CSS_LB_GP_TIME_OFFLINE_GG_PROG     0x10000067
#define PROPERTY_CSS_LB_GP_TIME_ONLINE_GG_PROG      0x10000068
#define PROPERTY_CSS_LB_GP_TIME_OFFLINE_GG_SELECT   0x10000069
#define PROPERTY_CSS_LB_GP_TIME_ONLINE_GG_SELECT    0x1000006A
#define PROPERTY_CSS_LB_GP_TIME_OFFLINE_GG_BOMB     0x1000006B
#define PROPERTY_CSS_LB_GP_TIME_ONLINE_GG_BOMB      0x1000006C
#define PROPERTY_CSS_LB_GP_TIME_MAP_BANK            0x1000006D
#define PROPERTY_CSS_LB_GP_TIME_MAP_SHORTTRAIN      0x1000006E
#define PROPERTY_CSS_LB_GP_TIME_MAP_SHOOTS          0x1000006F
#define PROPERTY_CSS_LB_GP_TIME_MAP_STMARC          0x10000070
#define PROPERTY_CSS_LB_GP_TIME_MAP_SUGARCANE       0x10000071
#define PROPERTY_CSS_LB_GP_TIME_MAP_SAFEHOUSE       0x10000072
#define PROPERTY_CSS_LB_GP_TIME_MAP_LAKE            0x10000073
#define PROPERTY_CSS_LB_GP_TIME_MAP_BAGGAGE         0x10000074
#define PROPERTY_CSS_LB_GP_TIME_MAP_INFERNO         0x10000075
#define PROPERTY_CSS_LB_GP_TIME_MAP_ITALY           0x10000076
#define PROPERTY_CSS_LB_GP_TIME_MAP_OFFICE          0x10000077
#define PROPERTY_CSS_LB_GP_TIME_MAP_DUST2           0x10000078
#define PROPERTY_CSS_LB_GP_TIME_MAP_NUKE            0x10000079
#define PROPERTY_CSS_LB_GP_TIME_MAP_DUST            0x1000007A
#define PROPERTY_CSS_LB_GP_TIME_MAP_AZTEC           0x1000007B
#define PROPERTY_CSS_LB_KD_SHOTS                    0x1000007F
#define PROPERTY_CSS_LB_KD_HEADSHOTS                0x10000080
#define PROPERTY_CSS_LB_GP_TIME_PLAYED_CT           0x10000081
#define PROPERTY_CSS_LB_GP_TIME_PLAYED_T            0x10000082
#define PROPERTY_CSS_LB_KD_DEATHS                   0x10000083
#define PROPERTY_CSS_LB_KD_HITS                     0x10000084
#define PROPERTY_CSS_LB_WINS_LOSS_AS_CT             0x10000085
#define PROPERTY_CSS_LB_WINS_LOSS_AS_T              0x10000086
#define PROPERTY_CSS_SEARCH_LISTEN_SERVER           0x10000087
#define PROPERTY_CSS_MAX_OPEN_TEAM_SLOTS            0x10000089
#define PROPERTY_CSS_LB_GP_TIME_MAP_TRAIN           0x1000008A
#define PROPERTY_CSS_LB_GP_TIME_MAP_TRAINING        0x1000008B
#define PROPERTY_COLUMN_KILLS                       0x20000001
#define PROPERTY_CSS_LB_CS_AVERAGE_CONTRIB_SCORE    0x20000040
#define PROPERTY_CSS_LB_KD_KD_FORMULA               0x20000045
#define PROPERTY_CSS_LB_WINS_WIN_FORMULA            0x20000050
#define PROPERTY_CSS_LB_STARS_STARS                 0x20000058
#define PROPERTY_CSS_LB_GP_GAMES_PLAYED             0x2000005D
#define PROPERTY_CSS_LB_CS_ELO_RATING               0x20000088

//
// Achievement ids
//
// These values are used in the dwAchievementId member of the
// XUSER_ACHIEVEMENT structure that is used with
// XUserWriteAchievements and XUserCreateAchievementEnumerator.
//

#define ACHIEVEMENT_KILL_ENEMY_HIGH                 1
#define ACHIEVEMENT_MEDALIST                        2
#define ACHIEVEMENT_GIVE_DAMAGE_LOW                 3
#define ACHIEVEMENT_EARN_MONEY_LOW                  4
#define ACHIEVEMENT_GUN_GAME_RAMPAGE                5
#define ACHIEVEMENT_HEADSHOTS                       6
#define ACHIEVEMENT_FLAWLESS_VICTORY                7
#define ACHIEVEMENT_DOMINATIONS_LOW                 8
#define ACHIEVEMENT_KILL_WITH_EVERY_WEAPON          9
#define ACHIEVEMENT_KILL_ENEMY_LAST_BULLET          10
#define ACHIEVEMENT_GUN_GAME_FIRST_THING_FIRST      11
#define ACHIEVEMENT_GUN_GAME_ROUNDS_HIGH            12

//
// AvatarAssetAward ids
//


//
// Stats view ids
//
// These are used in the dwViewId member of the XUSER_STATS_SPEC structure
// passed to the XUserReadStats* and XUserCreateStatsEnumerator* functions.
//

// Skill leaderboards for ranked game modes

#define STATS_VIEW_SKILL_RANKED_CSS_GAME_MODE_MULTIPLAYER 0xFFFF0000

// Skill leaderboards for unranked (standard) game modes

#define STATS_VIEW_SKILL_STANDARD_CSS_GAME_MODE_MULTIPLAYER 0xFFFE0000

// Title defined leaderboards

#define STATS_VIEW_WINS_ONLINE_CASUAL               32
#define STATS_VIEW_WINS_ONLINE_COMPETITIVE          33
#define STATS_VIEW_WINS_ONLINE_GG_PROG              37
#define STATS_VIEW_WINS_ONLINE_GG_BOMB              39
#define STATS_VIEW_CS_ONLINE_CASUAL                 43
#define STATS_VIEW_CS_ONLINE_COMPETITIVE            44
#define STATS_VIEW_CS_ONLINE_GG_PROG                48
#define STATS_VIEW_CS_ONLINE_GG_BOMB                50
#define STATS_VIEW_KD_ONLINE_CASUAL                 54
#define STATS_VIEW_KD_ONLINE_COMPETITIVE            55
#define STATS_VIEW_KD_ONLINE_GG_PROG                59
#define STATS_VIEW_KD_ONLINE_GG_BOMB                61
#define STATS_VIEW_STARS_ONLINE_CASUAL              65
#define STATS_VIEW_STARS_ONLINE_COMPETITIVE         66
#define STATS_VIEW_STARS_ONLINE_GG_PROG             71
#define STATS_VIEW_STARS_ONLINE_GG_BOMB             73
#define STATS_VIEW_GP_ONLINE_CASUAL                 77
#define STATS_VIEW_GP_ONLINE_COMPETITIVE            78
#define STATS_VIEW_GP_ONLINE_GG_PROG                82
#define STATS_VIEW_GP_ONLINE_GG_BOMB                84

//
// Stats view column ids
//
// These ids are used to read columns of stats views.  They are specified in
// the rgwColumnIds array of the XUSER_STATS_SPEC structure.  Rank, rating
// and gamertag are not retrieved as custom columns and so are not included
// in the following definitions.  They can be retrieved from each row's
// header (e.g., pStatsResults->pViews[x].pRows[y].dwRank, etc.).
//

// Column ids for WINS_ONLINE_CASUAL

#define STATS_COLUMN_WINS_ONLINE_CASUAL_WINS_TOTAL  1
#define STATS_COLUMN_WINS_ONLINE_CASUAL_LOSSES_TOTAL 2
#define STATS_COLUMN_WINS_ONLINE_CASUAL_WIN_AS_CT   6
#define STATS_COLUMN_WINS_ONLINE_CASUAL_WIN_AS_T    7
#define STATS_COLUMN_WINS_ONLINE_CASUAL_LOSS_AS_CT  3
#define STATS_COLUMN_WINS_ONLINE_CASUAL_LOSS_AS_T   4

// Column ids for WINS_ONLINE_COMPETITIVE

#define STATS_COLUMN_WINS_ONLINE_COMPETITIVE_WINS_TOTAL 1
#define STATS_COLUMN_WINS_ONLINE_COMPETITIVE_LOSSES_TOTAL 2
#define STATS_COLUMN_WINS_ONLINE_COMPETITIVE_WIN_AS_CT 6
#define STATS_COLUMN_WINS_ONLINE_COMPETITIVE_WIN_AS_T 7
#define STATS_COLUMN_WINS_ONLINE_COMPETITIVE_LOSS_AS_CT 3
#define STATS_COLUMN_WINS_ONLINE_COMPETITIVE_LOSS_AS_T 4

// Column ids for WINS_ONLINE_GG_PROG

#define STATS_COLUMN_WINS_ONLINE_GG_PROG_WINS_TOTAL 1
#define STATS_COLUMN_WINS_ONLINE_GG_PROG_LOSSES_TOTAL 2
#define STATS_COLUMN_WINS_ONLINE_GG_PROG_WIN_AS_CT  6
#define STATS_COLUMN_WINS_ONLINE_GG_PROG_WIN_AS_T   7
#define STATS_COLUMN_WINS_ONLINE_GG_PROG_LOSS_AS_CT 3
#define STATS_COLUMN_WINS_ONLINE_GG_PROG_LOSS_AS_T  4

// Column ids for WINS_ONLINE_GG_BOMB

#define STATS_COLUMN_WINS_ONLINE_GG_BOMB_WINS_TOTAL 1
#define STATS_COLUMN_WINS_ONLINE_GG_BOMB_LOSSES_TOTAL 2
#define STATS_COLUMN_WINS_ONLINE_GG_BOMB_WIN_AS_CT  6
#define STATS_COLUMN_WINS_ONLINE_GG_BOMB_WIN_AS_T   7
#define STATS_COLUMN_WINS_ONLINE_GG_BOMB_LOSS_AS_CT 3
#define STATS_COLUMN_WINS_ONLINE_GG_BOMB_LOSS_AS_T  4

// Column ids for CS_ONLINE_CASUAL

#define STATS_COLUMN_CS_ONLINE_CASUAL_AVG_CONTRIB_SCORE 2
#define STATS_COLUMN_CS_ONLINE_CASUAL_MVP_AWARDS    4
#define STATS_COLUMN_CS_ONLINE_CASUAL_TOTAL_ROUNDS_PLAYED 5
#define STATS_COLUMN_CS_ONLINE_CASUAL_TOTAL_CONTRIB_SCORE 6
#define STATS_COLUMN_CS_ONLINE_CASUAL_TOTAL_KILLS   7
#define STATS_COLUMN_CS_ONLINE_CASUAL_TOTAL_DEATHS  8
#define STATS_COLUMN_CS_ONLINE_CASUAL_TOTAL_DAMAGE  9

// Column ids for CS_ONLINE_COMPETITIVE

#define STATS_COLUMN_CS_ONLINE_COMPETITIVE_AVG_CONTRIB_SCORE 2
#define STATS_COLUMN_CS_ONLINE_COMPETITIVE_MVP_AWARDS 4
#define STATS_COLUMN_CS_ONLINE_COMPETITIVE_TOTAL_ROUNDS_PLAYED 5
#define STATS_COLUMN_CS_ONLINE_COMPETITIVE_TOTAL_CONTRIB_SCORE 6
#define STATS_COLUMN_CS_ONLINE_COMPETITIVE_TOTAL_KILLS 7
#define STATS_COLUMN_CS_ONLINE_COMPETITIVE_TOTAL_DEATHS 8
#define STATS_COLUMN_CS_ONLINE_COMPETITIVE_TOTAL_DAMAGE 9

// Column ids for CS_ONLINE_GG_PROG

#define STATS_COLUMN_CS_ONLINE_GG_PROG_AVG_CONTRIB_SCORE 2
#define STATS_COLUMN_CS_ONLINE_GG_PROG_MVP_AWARDS   4
#define STATS_COLUMN_CS_ONLINE_GG_PROG_TOTAL_ROUNDS_PLAYED 5
#define STATS_COLUMN_CS_ONLINE_GG_PROG_TOTAL_CONTRIB_SCORE 6
#define STATS_COLUMN_CS_ONLINE_GG_PROG_TOTAL_KILLS  7
#define STATS_COLUMN_CS_ONLINE_GG_PROG_TOTAL_DEATHS 8
#define STATS_COLUMN_CS_ONLINE_GG_PROG_TOTAL_DAMAGE 9

// Column ids for CS_ONLINE_GG_BOMB

#define STATS_COLUMN_CS_ONLINE_GG_BOMB_AVG_CONTRIB_SCORE 2
#define STATS_COLUMN_CS_ONLINE_GG_BOMB_MVP_AWARDS   4
#define STATS_COLUMN_CS_ONLINE_GG_BOMB_TOTAL_ROUNDS_PLAYED 5
#define STATS_COLUMN_CS_ONLINE_GG_BOMB_TOTAL_CONTRIB_SCORE 6
#define STATS_COLUMN_CS_ONLINE_GG_BOMB_TOTAL_KILLS  7
#define STATS_COLUMN_CS_ONLINE_GG_BOMB_TOTAL_DEATHS 8
#define STATS_COLUMN_CS_ONLINE_GG_BOMB_TOTAL_DAMAGE 9

// Column ids for KD_ONLINE_CASUAL

#define STATS_COLUMN_KD_ONLINE_CASUAL_TOTAL_KILLS   4
#define STATS_COLUMN_KD_ONLINE_CASUAL_TOTAL_SHOTS   5
#define STATS_COLUMN_KD_ONLINE_CASUAL_TOTAL_HEADSHOTS 6
#define STATS_COLUMN_KD_ONLINE_CASUAL_TOTAL_DEATHS  1
#define STATS_COLUMN_KD_ONLINE_CASUAL_TOTAL_HITS    2

// Column ids for KD_ONLINE_COMPETITIVE

#define STATS_COLUMN_KD_ONLINE_COMPETITIVE_TOTAL_KILLS 4
#define STATS_COLUMN_KD_ONLINE_COMPETITIVE_TOTAL_SHOTS 5
#define STATS_COLUMN_KD_ONLINE_COMPETITIVE_TOTAL_HEADSHOTS 6
#define STATS_COLUMN_KD_ONLINE_COMPETITIVE_TOTAL_DEATHS 1
#define STATS_COLUMN_KD_ONLINE_COMPETITIVE_TOTAL_HITS 2

// Column ids for KD_ONLINE_GG_PROG

#define STATS_COLUMN_KD_ONLINE_GG_PROG_TOTAL_KILLS  4
#define STATS_COLUMN_KD_ONLINE_GG_PROG_TOTAL_SHOTS  5
#define STATS_COLUMN_KD_ONLINE_GG_PROG_TOTAL_HEADSHOTS 6
#define STATS_COLUMN_KD_ONLINE_GG_PROG_TOTAL_DEATHS 1
#define STATS_COLUMN_KD_ONLINE_GG_PROG_TOTAL_HITS   2

// Column ids for KD_ONLINE_GG_BOMB

#define STATS_COLUMN_KD_ONLINE_GG_BOMB_TOTAL_KILLS  4
#define STATS_COLUMN_KD_ONLINE_GG_BOMB_TOTAL_SHOTS  5
#define STATS_COLUMN_KD_ONLINE_GG_BOMB_TOTAL_HEADSHOTS 6
#define STATS_COLUMN_KD_ONLINE_GG_BOMB_TOTAL_DEATHS 1
#define STATS_COLUMN_KD_ONLINE_GG_BOMB_TOTAL_HITS   2

// Column ids for STARS_ONLINE_CASUAL

#define STATS_COLUMN_STARS_ONLINE_CASUAL_BOMBS_PLANTED 1
#define STATS_COLUMN_STARS_ONLINE_CASUAL_BOMBS_DETONATED 2
#define STATS_COLUMN_STARS_ONLINE_CASUAL_BOMBS_DEFUSED 3
#define STATS_COLUMN_STARS_ONLINE_CASUAL_HOSTAGES_RESCUED 4

// Column ids for STARS_ONLINE_COMPETITIVE

#define STATS_COLUMN_STARS_ONLINE_COMPETITIVE_BOMBS_PLANTED 1
#define STATS_COLUMN_STARS_ONLINE_COMPETITIVE_BOMBS_DETONATED 2
#define STATS_COLUMN_STARS_ONLINE_COMPETITIVE_BOMBS_DEFUSED 3
#define STATS_COLUMN_STARS_ONLINE_COMPETITIVE_HOSTAGES_RESCUED 4

// Column ids for STARS_ONLINE_GG_PROG

#define STATS_COLUMN_STARS_ONLINE_GG_PROG_BOMBS_PLANTED 1
#define STATS_COLUMN_STARS_ONLINE_GG_PROG_BOMBS_DETONATED 2
#define STATS_COLUMN_STARS_ONLINE_GG_PROG_BOMBS_DEFUSED 3
#define STATS_COLUMN_STARS_ONLINE_GG_PROG_HOSTAGES_RESCUED 4

// Column ids for STARS_ONLINE_GG_BOMB

#define STATS_COLUMN_STARS_ONLINE_GG_BOMB_BOMBS_PLANTED 1
#define STATS_COLUMN_STARS_ONLINE_GG_BOMB_BOMBS_DETONATED 2
#define STATS_COLUMN_STARS_ONLINE_GG_BOMB_BOMBS_DEFUSED 3
#define STATS_COLUMN_STARS_ONLINE_GG_BOMB_HOSTAGES_RESCUED 4

// Column ids for GP_ONLINE_CASUAL

#define STATS_COLUMN_GP_ONLINE_CASUAL_TIME_PLAYED   1
#define STATS_COLUMN_GP_ONLINE_CASUAL_TIME_PLAYED_CT 2
#define STATS_COLUMN_GP_ONLINE_CASUAL_TIME_PLAYED_T 3
#define STATS_COLUMN_GP_ONLINE_CASUAL_TOTAL_MEDALS  4
#define STATS_COLUMN_GP_ONLINE_CASUAL_TIME_PLAYED_MAP_BANK 5
#define STATS_COLUMN_GP_ONLINE_CASUAL_TIME_PLAYED_MAP_SHORTTRAIN 6
#define STATS_COLUMN_GP_ONLINE_CASUAL_TIME_PLAYED_MAP_SHOOTS 7
#define STATS_COLUMN_GP_ONLINE_CASUAL_TIME_PLAYED_MAP_STMARC 8
#define STATS_COLUMN_GP_ONLINE_CASUAL_TIME_PLAYED_MAP_SUGARCANE 9
#define STATS_COLUMN_GP_ONLINE_CASUAL_TIME_PLAYED_MAP_SAFEHOUSE 10
#define STATS_COLUMN_GP_ONLINE_CASUAL_TIME_PLAYED_MAP_LAKE 11
#define STATS_COLUMN_GP_ONLINE_CASUAL_TIME_PLAYED_MAP_BAGGAGE 12
#define STATS_COLUMN_GP_ONLINE_CASUAL_TIME_PLAYED_MAP_INFERNO 13
#define STATS_COLUMN_GP_ONLINE_CASUAL_TIME_PLAYED_MAP_ITALY 14
#define STATS_COLUMN_GP_ONLINE_CASUAL_TIME_PLAYED_MAP_OFFICE 15
#define STATS_COLUMN_GP_ONLINE_CASUAL_TIME_PLAYED_MAP_DUST2 16
#define STATS_COLUMN_GP_ONLINE_CASUAL_TIME_PLAYED_MAP_NUKE 17
#define STATS_COLUMN_GP_ONLINE_CASUAL_TIME_PLAYED_MAP_DUST 18
#define STATS_COLUMN_GP_ONLINE_CASUAL_TIME_PLAYED_MAP_AZTEC 19
#define STATS_COLUMN_GP_ONLINE_CASUAL_TIME_PLAYED_MAP_TRAIN 20
#define STATS_COLUMN_GP_ONLINE_CASUAL_TIME_PLAYED_MAP_TRAINING 21

// Column ids for GP_ONLINE_COMPETITIVE

#define STATS_COLUMN_GP_ONLINE_COMPETITIVE_TIME_PLAYED 1
#define STATS_COLUMN_GP_ONLINE_COMPETITIVE_TIME_PLAYED_CT 2
#define STATS_COLUMN_GP_ONLINE_COMPETITIVE_TIME_PLAYED_T 3
#define STATS_COLUMN_GP_ONLINE_COMPETITIVE_TOTAL_MEDALS 4
#define STATS_COLUMN_GP_ONLINE_COMPETITIVE_TIME_PLAYED_MAP_BANK 5
#define STATS_COLUMN_GP_ONLINE_COMPETITIVE_TIME_PLAYED_MAP_SHORTTRAIN 6
#define STATS_COLUMN_GP_ONLINE_COMPETITIVE_TIME_PLAYED_MAP_SHOOTS 7
#define STATS_COLUMN_GP_ONLINE_COMPETITIVE_TIME_PLAYED_MAP_STMARC 8
#define STATS_COLUMN_GP_ONLINE_COMPETITIVE_TIME_PLAYED_MAP_SUGARCANE 9
#define STATS_COLUMN_GP_ONLINE_COMPETITIVE_TIME_PLAYED_MAP_SAFEHOUSE 10
#define STATS_COLUMN_GP_ONLINE_COMPETITIVE_TIME_PLAYED_MAP_LAKE 11
#define STATS_COLUMN_GP_ONLINE_COMPETITIVE_TIME_PLAYED_MAP_BAGGAGE 12
#define STATS_COLUMN_GP_ONLINE_COMPETITIVE_TIME_PLAYED_MAP_INFERNO 13
#define STATS_COLUMN_GP_ONLINE_COMPETITIVE_TIME_PLAYED_MAP_ITALY 14
#define STATS_COLUMN_GP_ONLINE_COMPETITIVE_TIME_PLAYED_MAP_OFFICE 15
#define STATS_COLUMN_GP_ONLINE_COMPETITIVE_TIME_PLAYED_MAP_DUST2 16
#define STATS_COLUMN_GP_ONLINE_COMPETITIVE_TIME_PLAYED_MAP_NUKE 17
#define STATS_COLUMN_GP_ONLINE_COMPETITIVE_TIME_PLAYED_MAP_DUST 18
#define STATS_COLUMN_GP_ONLINE_COMPETITIVE_TIME_PLAYED_MAP_AZTEC 19
#define STATS_COLUMN_GP_ONLINE_COMPETITIVE_TIME_PLAYED_MAP_TRAIN 20
#define STATS_COLUMN_GP_ONLINE_COMPETITIVE_TIME_PLAYED_MAP_TRAINING 21

// Column ids for GP_ONLINE_GG_PROG

#define STATS_COLUMN_GP_ONLINE_GG_PROG_TIME_PLAYED  1
#define STATS_COLUMN_GP_ONLINE_GG_PROG_TIME_PLAYED_CT 2
#define STATS_COLUMN_GP_ONLINE_GG_PROG_TIME_PLAYED_T 3
#define STATS_COLUMN_GP_ONLINE_GG_PROG_TOTAL_MEDALS 4
#define STATS_COLUMN_GP_ONLINE_GG_PROG_TIME_PLAYED_MAP_BANK 5
#define STATS_COLUMN_GP_ONLINE_GG_PROG_TIME_PLAYED_MAP_SHORTTRAIN 6
#define STATS_COLUMN_GP_ONLINE_GG_PROG_TIME_PLAYED_MAP_SHOOTS 7
#define STATS_COLUMN_GP_ONLINE_GG_PROG_TIME_PLAYED_MAP_STMARC 8
#define STATS_COLUMN_GP_ONLINE_GG_PROG_TIME_PLAYED_MAP_SUGARCANE 9
#define STATS_COLUMN_GP_ONLINE_GG_PROG_TIME_PLAYED_MAP_SAFEHOUSE 10
#define STATS_COLUMN_GP_ONLINE_GG_PROG_TIME_PLAYED_MAP_LAKE 11
#define STATS_COLUMN_GP_ONLINE_GG_PROG_TIME_PLAYED_MAP_BAGGAGE 12
#define STATS_COLUMN_GP_ONLINE_GG_PROG_TIME_PLAYED_MAP_INFERNO 13
#define STATS_COLUMN_GP_ONLINE_GG_PROG_TIME_PLAYED_MAP_ITALY 14
#define STATS_COLUMN_GP_ONLINE_GG_PROG_TIME_PLAYED_MAP_OFFICE 15
#define STATS_COLUMN_GP_ONLINE_GG_PROG_TIME_PLAYED_MAP_DUST2 16
#define STATS_COLUMN_GP_ONLINE_GG_PROG_TIME_PLAYED_MAP_NUKE 17
#define STATS_COLUMN_GP_ONLINE_GG_PROG_TIME_PLAYED_MAP_DUST 18
#define STATS_COLUMN_GP_ONLINE_GG_PROG_TIME_PLAYED_MAP_AZTEC 19
#define STATS_COLUMN_GP_ONLINE_GG_PROG_TIME_PLAYED_MAP_TRAIN 20
#define STATS_COLUMN_GP_ONLINE_GG_PROG_TIME_PLAYED_MAP_TRAINING 21

// Column ids for GP_ONLINE_GG_BOMB

#define STATS_COLUMN_GP_ONLINE_GG_BOMB_TIME_PLAYED  1
#define STATS_COLUMN_GP_ONLINE_GG_BOMB_TIME_PLAYED_CT 2
#define STATS_COLUMN_GP_ONLINE_GG_BOMB_TIME_PLAYED_T 3
#define STATS_COLUMN_GP_ONLINE_GG_BOMB_TOTAL_MEDALS 4
#define STATS_COLUMN_GP_ONLINE_GG_BOMB_TIME_PLAYED_MAP_BANK 5
#define STATS_COLUMN_GP_ONLINE_GG_BOMB_TIME_PLAYED_MAP_SHORTTRAIN 6
#define STATS_COLUMN_GP_ONLINE_GG_BOMB_TIME_PLAYED_MAP_SHOOTS 7
#define STATS_COLUMN_GP_ONLINE_GG_BOMB_TIME_PLAYED_MAP_STMARC 8
#define STATS_COLUMN_GP_ONLINE_GG_BOMB_TIME_PLAYED_MAP_SUGARCANE 9
#define STATS_COLUMN_GP_ONLINE_GG_BOMB_TIME_PLAYED_MAP_SAFEHOUSE 10
#define STATS_COLUMN_GP_ONLINE_GG_BOMB_TIME_PLAYED_MAP_LAKE 11
#define STATS_COLUMN_GP_ONLINE_GG_BOMB_TIME_PLAYED_MAP_BAGGAGE 12
#define STATS_COLUMN_GP_ONLINE_GG_BOMB_TIME_PLAYED_MAP_INFERNO 13
#define STATS_COLUMN_GP_ONLINE_GG_BOMB_TIME_PLAYED_MAP_ITALY 14
#define STATS_COLUMN_GP_ONLINE_GG_BOMB_TIME_PLAYED_MAP_OFFICE 15
#define STATS_COLUMN_GP_ONLINE_GG_BOMB_TIME_PLAYED_MAP_DUST2 16
#define STATS_COLUMN_GP_ONLINE_GG_BOMB_TIME_PLAYED_MAP_NUKE 17
#define STATS_COLUMN_GP_ONLINE_GG_BOMB_TIME_PLAYED_MAP_DUST 18
#define STATS_COLUMN_GP_ONLINE_GG_BOMB_TIME_PLAYED_MAP_AZTEC 19
#define STATS_COLUMN_GP_ONLINE_GG_BOMB_TIME_PLAYED_MAP_TRAIN 20
#define STATS_COLUMN_GP_ONLINE_GG_BOMB_TIME_PLAYED_MAP_TRAINING 21

//
// Matchmaking queries
//
// These values are passed as the dwProcedureIndex parameter to
// XSessionSearch to indicate which matchmaking query to run.
//

#define SESSION_MATCH_QUERY_PLAYER_MATCH            1
#define SESSION_MATCH_QUERY_ALL_SESSIONS            3
#define SESSION_MATCH_QUERY_PLAYER_MATCH_ANY_LEVEL  4
#define SESSION_MATCH_QUERY_PLAYER_MATCH_TEAM       5
#define SESSION_MATCH_QUERY_ALL_SESSIONS_TEAM       6
#define SESSION_MATCH_QUERY_PLAYER_MATCH_ANY_LEVEL_TEAM 7

//
// Gamer pictures
//
// These ids are passed as the dwPictureId parameter to XUserAwardGamerTile.
//


//
// Strings
//
// These ids are passed as the dwStringId parameter to XReadStringsFromSpaFile.
//

#define SPASTRING_ACHVNAME_KILL_ENEMY_HIGH          7
#define SPASTRING_ACHVDESC_KILL_ENEMY_HIGH          8
#define SPASTRING_ACHVNAME_MEDALIST                 9
#define SPASTRING_ACHVDESC_MEDALIST                 10
#define SPASTRING_ACH_GIVE_DAMAGE_LOW_NAME          11
#define SPASTRING_ACH_GIVE_DAMAGE_LOW_HOWTO         12
#define SPASTRING_ACH_EARN_MONEY_LOW_NAME           13
#define SPASTRING_ACH_EARN_MONEY_LOW_HOWTO          14
#define SPASTRING_ACH_GUN_GAME_RAMPAGE_NAME         15
#define SPASTRING_ACH_GUN_GAME_RAMPAGE_HOWTO        16
#define SPASTRING_ACHVNAME_HEADSHOTS                17
#define SPASTRING_ACHVDESC_HEADSHOTS                18
#define SPASTRING_ACHVNAME_FLAWLESS_VICTORY         19
#define SPASTRING_ACHVDESC_FLAWLESS_VICTORY         20
#define SPASTRING_ACHVNAME_DOMINATIONS_LOW          21
#define SPASTRING_ACHVDESC_DOMINATIONS_LOW          22
#define SPASTRING_ACHVNAME_KILL_WITH_EVERY_WEAPON   23
#define SPASTRING_ACHVDESC_KILL_WITH_EVERY_WEAPON   24
#define SPASTRING_ACHVNAME_KILL_ENEMY_LAST_BULLET   25
#define SPASTRING_ACHVDESC_KILL_ENEMY_LAST_BULLET   26
#define SPASTRING_ACH_GUN_GAME_FIRST_THING_FIRST_NAME 27
#define SPASTRING_ACH_GUN_GAME_FIRST_THING_FIRST_HOWTO 28
#define SPASTRING_ACH_GUN_GAME_ROUNDS_HIGH_NAME     29
#define SPASTRING_ACH_GUN_GAME_ROUNDS_HIGH_HOWTO    30
#define SPASTRING_GAMEMODE_MULTIPLAYER              31
#define SPASTRING_IDLE                              33
#define SPASTRING_COLUMN_KILLS_NAME                 35
#define SPASTRING_CSS_MAP_NAME                      36
#define SPASTRING_MAP_AZTEC                         37
#define SPASTRING_MAP_ITALY                         41
#define SPASTRING_MAP_OFFICE                        43
#define SPASTRING_MAP_DUST                          46
#define SPASTRING_MAP_DUST2                         47
#define SPASTRING_MAP_INFERNO                       48
#define SPASTRING_MAP_NUKE                          49
#define SPASTRING_MAINMENU                          62
#define SPASTRING_GAME_STATE_NAME                   64
#define SPASTRING_CSS_AGGREGATE_EXPERIENCE_NAME     68
#define SPASTRING_PROPERTY_CSS_AGGREGATE_SKILL0_NAME 69
#define SPASTRING_CSS_AGGREGATE_SKILL1_NAME         70
#define SPASTRING_CSS_AGGREGATE_SKILL2_NAME         71
#define SPASTRING_CSS_AGGREGATE_SKILL3_NAME         72
#define SPASTRING_CSS_AGGREGATE_SKILL4_NAME         73
#define SPASTRING_CSS_MATCH_VERSION_NAME            76
#define SPASTRING_CSS_OPEN_SLOTS_NAME               77
#define SPASTRING_CSS_SEARCH_EXP_MAX_NAME           87
#define SPASTRING_CSS_SEARCH_EXP_MIN_NAME           88
#define SPASTRING_CSS_SEARCH_SKILL0_MAX_NAME        89
#define SPASTRING_CSS_SEARCH_SKILL0_MIN_NAME        90
#define SPASTRING_CSS_SEARCH_SKILL1_MAX_NAME        91
#define SPASTRING_CSS_SEARCH_SKILL1_MIN_NAME        92
#define SPASTRING_CSS_SEARCH_SKILL2_MAX_NAME        93
#define SPASTRING_CSS_SEARCH_SKILL2_MIN_NAME        94
#define SPASTRING_CSS_SEARCH_SKILL3_MAX_NAME        95
#define SPASTRING_CSS_SEARCH_SKILL3_MIN_NAME        96
#define SPASTRING_CSS_SEARCH_SKILL4_MAX_NAME        97
#define SPASTRING_CSS_SEARCH_SKILL4_MIN_NAME        98
#define SPASTRING_CSS_TEAM_NAME                     132
#define SPASTRING_CSS_GAME_STATE_SINGLE_PLAYER      172
#define SPASTRING_CSS_GAME_STATE_MULTIPLAYER        173
#define SPASTRING_CSS_GAME_STATE_IN_MENUS           175
#define SPASTRING_CSS_GAME_MODE_CASUAL_NAME         176
#define SPASTRING_CSS_GAME_MODE_COMPETITIVE         177
#define SPASTRING_CSS_GAME_MODE_FREESTYLE           179
#define SPASTRING_CSS_TEAM_CT_NAME                  180
#define SPASTRING_CSS_TEAM_T_NAME                   181
#define SPASTRING_CSS_GAME_MODE_NAME                182
#define SPASTRING_CSS_PRIVACY_NAME                  183
#define SPASTRING_CSS_PRIVACY_PUBLIC_NAME           184
#define SPASTRING_CSS_PRIVACY_FRIENDS_NAME          185
#define SPASTRING_CSS_PRIVACY_INVITE_ONLY_NAME      186
#define SPASTRING_MULTIPLAYER                       187
#define SPASTRING_MULTIPLAYER_NO_SLOTS              188
#define SPASTRING_MULTIPLAYER_PRIVATE               189
#define SPASTRING_SINGLEPLAYER                      190
#define SPASTRING_CSS_TEAM_SPECTATOR_NAME           191
#define SPASTRING_CSS_GAME_MODE_AS_NUMBER           192
#define SPASTRING_ACHVDESC_KILL_ENEMY_HIGH_1        272
#define SPASTRING_ACHVDESC_MEDALIST_1               273
#define SPASTRING_ACH_GIVE_DAMAGE_LOW_DESC          274
#define SPASTRING_ACH_EARN_MONEY_LOW_DESC           275
#define SPASTRING_ACH_GUN_GAME_RAMPAGE_DESC         276
#define SPASTRING_ACHVDESC_HEADSHOTS_1              277
#define SPASTRING_ACHVDESC_FLAWLESS_VICTORY_1       278
#define SPASTRING_ACHVDESC_DOMINATIONS_LOW_1        279
#define SPASTRING_ACHVDESC_KILL_WITH_EVERY_WEAPON_1 280
#define SPASTRING_ACHVDESC_KILL_ENEMY_LAST_BULLET_1 281
#define SPASTRING_ACH_GUN_GAME_FIRST_THING_FIRST_DESC 282
#define SPASTRING_ACH_GUN_GAME_ROUNDS_HIGH_DESC     283
#define SPASTRING_CT_CSS_GAME_TYPE_NAME             286
#define SPASTRING_CV_CSS_GAME_TYPE_CLASSIC_NAME     287
#define SPASTRING_CV_CSS_GAME_TYPE_GUNGAME_NAME     288
#define SPASTRING_CV_CSS_LEVEL_BAGGAGE_NAME         291
#define SPASTRING_CV_CSS_LEVEL_SHOOTS_NAME          293
#define SPASTRING_CV_CSS_LEVEL_LAKE_NAME            295
#define SPASTRING_CV_CSS_LEVEL_BANK_NAME            296
#define SPASTRING_CV_CSS_LEVEL_SAFEHOUSE_NAME       302
#define SPASTRING_CV_CSS_LEVEL_SUGARCANE_NAME       304
#define SPASTRING_CV_CSS_LEVEL_STMARC_NAME          306
#define SPASTRING_PROPERTY_CSS_LB_CS_AVERAGE_CONTRIB_SCORE_NAME 307
#define SPASTRING_PROPERTY_CSS_LB_CS_AVERAGE_KILLS_PER_ROUND_NAME 308
#define SPASTRING_LB_CS_ONLINE_GG_PROG_AVG_CONTRIB_SCORE_NAME 310
#define SPASTRING_PROPERTY_CSS_LB_CS_AVERAGE_DEATHS_PER_ROUND_NAME 312
#define SPASTRING_PROPERTY_CSS_LB_CS_AVERAGE_DAMAGE_PER_ROUND_NAME 313
#define SPASTRING_PROPERTY_CSS_LB_CS_MVP_AWARDS_MONTH_NAME 314
#define SPASTRING_PROPERTY_CSS_LB_KD_KD_FORMULA_NAME 315
#define SPASTRING_PROPERTY_CSS_LB_KD_KD_ACTUAL_NAME 316
#define SPASTRING_PROPERTY_CSS_LB_KD_HEADSHOT_PERCENT_NAME 317
#define SPASTRING_PROPERTY_CSS_LB_KD_HITS_PERCENT_NAME 318
#define SPASTRING_PROPERTY_CSS_LB_KD_KILLS_NAME     319
#define SPASTRING_LB_CS_ONLINE_GG_PROG_MVP_AWARDS_NAME 322
#define SPASTRING_PROPERTY_CSS_LB_CS_TOTAL_ROUNDS_PLAYED_NAME 324
#define SPASTRING_PROPERTY_CSS_LB_CS_TOTAL_KILLS_NAME 325
#define SPASTRING_PROPERTY_CSS_LB_CS_TOTAL_DEATHS_NAME 326
#define SPASTRING_PROPERTY_CSS_LB_CS_TOTAL_DAMAGE_NAME 327
#define SPASTRING_PROPERTY_CSS_LB_CS_TOTAL_CONTRIB_SCORE_NAME 328
#define SPASTRING_LB_CS_ONLINE_GG_PROG_TOTAL_ROUNDS_PLAYED_NAME 329
#define SPASTRING_LB_CS_ONLINE_GG_PROG_TOTAL_CONTRIB_SCORE_NAME 330
#define SPASTRING_LB_CS_ONLINE_GG_PROG_TOTAL_KILLS_NAME 331
#define SPASTRING_LB_CS_ONLINE_GG_PROG_TOTAL_DEATHS_NAME 332
#define SPASTRING_LB_CS_ONLINE_GG_PROG_TOTAL_DAMAGE_NAME 333
#define SPASTRING_LB_KD_ONLINE_CASUAL_KD_RANKED_NAME 334
#define SPASTRING_LB_KD_ONLINE_CASUAL_TOTAL_KILLS_NAME 338
#define SPASTRING_PROPERTY_CSS_LB_WINS_WIN_FORMULA_NAME 339
#define SPASTRING_PROPERTY_CSS_LB_WINS_WINS_NAME    340
#define SPASTRING_PROPERTY_CSS_LB_WINS_LOSSES_NAME  341
#define SPASTRING_PROPERTY_CSS_LB_WINS_WIN_PERCENT_AS_CT_NAME 342
#define SPASTRING_PROPERTY_CSS_LB_WINS_WIN_PERCENT_AS_T_NAME 343
#define SPASTRING_PROPERTY_CSS_LB_WINS_WIN_PERCENT_NAME 344
#define SPASTRING_PROPERTY_CSS_LB_WINS_WIN_AS_CT_NAME 345
#define SPASTRING_PROPERTY_CSS_LB_WINS_WIN_AS_T_NAME 346
#define SPASTRING_LB_WINS_OFFLINE_GG_BOMB_WINS_RANKED_NAME 347
#define SPASTRING_LB_WINS_OFFLINE_GG_BOMB_WINS_TOTAL_NAME 348
#define SPASTRING_LB_WINS_OFFLINE_GG_BOMB_LOSSES_TOTAL_NAME 349
#define SPASTRING_PROPERTY_CSS_LB_STARS_STARS_NAME  353
#define SPASTRING_PROPERTY_CSS_LB_STARS_BOMBS_PLANTED_NAME 354
#define SPASTRING_PROPERTY_CSS_LB_STARS_BOMBS_DETONATED_NAME 355
#define SPASTRING_PROPERTY_CSS_LB_STARS_BOMBS_DEFUSED_NAME 356
#define SPASTRING_PROPERTY_CSS_LB_STARS_HOSTAGES_RESCUED_NAME 357
#define SPASTRING_LB_STARS_ONLINE_CASUAL_TOTAL_STARS_NAME 358
#define SPASTRING_LB_STARS_ONLINE_CASUAL_BOMBS_PLANTED_NAME 359
#define SPASTRING_LB_STARS_ONLINE_CASUAL_BOMBS_DETONATED_NAME 360
#define SPASTRING_LB_STARS_ONLINE_CASUAL_BOMBS_DEFUSED_NAME 361
#define SPASTRING_LB_STARS_ONLINE_CASUAL_HOSTAGES_RESCUED_NAME 362
#define SPASTRING_PROPERTY_CSS_LB_GP_GAMES_PLAYED_NAME 363
#define SPASTRING_PROPERTY_CSS_LB_GP_TIME_PLAYED_NAME 364
#define SPASTRING_PROPERTY_CSS_LB_GP_PLAYED_CT_PERCENT_NAME 365
#define SPASTRING_PROPERTY_CSS_LB_GP_PLAYED_T_PERCENT_NAME 366
#define SPASTRING_PROPERTY_CSS_LB_GP_TOTAL_MEDALS_NAME 367
#define SPASTRING_PROPERTY_CSS_LB_GP_TIME_OFFLINE_CASUAL_NAME 368
#define SPASTRING_PROPERTY_CSS_LB_GP_TIME_OFFLINE_COMPETITIVE_NAME 369
#define SPASTRING_PROPERTY_CSS_LB_GP_TIME_ONLINE_CASUAL_NAME 370
#define SPASTRING_PROPERTY_CSS_LB_GP_TIME_ONLINE_COMPETITIVE_NAME 371
#define SPASTRING_PROPERTY_CSS_LB_GP_TIME_ONLINE_PRIVATE_NAME 372
#define SPASTRING_PROPERTY_CSS_LB_GP_TIME_OFFLINE_GG_PROG_NAME 373
#define SPASTRING_PROPERTY_CSS_LB_GP_TIME_ONLINE_GG_PROG_NAME 374
#define SPASTRING_PROPERTY_CSS_LB_GP_TIME_OFFLINE_GG_SELECT_NAME 375
#define SPASTRING_PROPERTY_CSS_LB_GP_TIME_ONLINE_GG_SELECT_NAME 376
#define SPASTRING_PROPERTY_CSS_LB_GP_TIME_OFFLINE_GG_BOMB_NAME 377
#define SPASTRING_PROPERTY_CSS_LB_GP_TIME_ONLINE_GG_BOMB_NAME 378
#define SPASTRING_PROPERTY_CSS_LB_GP_TIME_MAP_BANK_NAME 379
#define SPASTRING_PROPERTY_CSS_LB_GP_TIME_MAP_SHORTTRAIN_NAME 380
#define SPASTRING_PROPERTY_CSS_LB_GP_TIME_MAP_SHOOTS_NAME 381
#define SPASTRING_PROPERTY_CSS_LB_GP_TIME_MAP_STMARC_NAME 382
#define SPASTRING_PROPERTY_CSS_LB_GP_TIME_MAP_SUGARCANE_NAME 383
#define SPASTRING_PROPERTY_CSS_LB_GP_TIME_MAP_SAFEHOUSE_NAME 384
#define SPASTRING_PROPERTY_CSS_LB_GP_TIME_MAP_LAKE_NAME 385
#define SPASTRING_PROPERTY_CSS_LB_GP_TIME_MAP_BAGGAGE_NAME 386
#define SPASTRING_PROPERTY_CSS_LB_GP_TIME_MAP_INFERNO_NAME 387
#define SPASTRING_PROPERTY_CSS_LB_GP_TIME_MAP_ITALY_NAME 388
#define SPASTRING_PROPERTY_CSS_LB_GP_TIME_MAP_OFFICE_NAME 389
#define SPASTRING_PROPERTY_CSS_LB_GP_TIME_MAP_DUST2_NAME 390
#define SPASTRING_PROPERTY_CSS_LB_GP_TIME_MAP_NUKE_NAME 391
#define SPASTRING_PROPERTY_CSS_LB_GP_TIME_MAP_DUST_NAME 392
#define SPASTRING_PROPERTY_CSS_LB_GP_TIME_MAP_AZTEC_NAME 393
#define SPASTRING_LB_GP_ONLINE_CASUAL_GAMES_PLAYED_NAME 397
#define SPASTRING_LB_WINS_ONLINE_COMPETITIVE_NAME   398
#define SPASTRING_LB_GP_ONLINE_CASUAL_TIME_PLAYED_NAME 400
#define SPASTRING_LB_GP_ONLINE_CASUAL_TOTAL_MEDALS_NAME 403
#define SPASTRING_LB_GP_ONLINE_CASUAL_TIME_PLAYED_MAP_BANK_NAME 406
#define SPASTRING_LB_GAMES_PLAYED_TIME_PLAYED_MAP_SHORTTRAIN_NAME 407
#define SPASTRING_LB_GAMES_PLAYED_TIME_PLAYED_MAP_SHOOTS_NAME 408
#define SPASTRING_LB_GAMES_PLAYED_TIME_PLAYED_MAP_STMARC_NAME 409
#define SPASTRING_LB_GAMES_PLAYED_TIME_PLAYED_MAP_SUGARCANE_NAME 410
#define SPASTRING_LB_GAMES_PLAYED_TIME_PLAYED_MAP_SAFEHOUSE_NAME 411
#define SPASTRING_LB_GAMES_PLAYED_TIME_PLAYED_MAP_LAKE_NAME 412
#define SPASTRING_LB_GP_ONLINE_CASUAL_TIME_PLAYED_MAP_BAGGAGE_NAME 413
#define SPASTRING_LB_GP_ONLINE_CASUAL_TIME_PLAYED_MAP_INFERNO_NAME 414
#define SPASTRING_LB_GP_ONLINE_CASUAL_TIME_PLAYED_MAP_ITALY_NAME 415
#define SPASTRING_LB_GP_ONLINE_CASUAL_TIME_PLAYED_MAP_OFFICE_NAME 416
#define SPASTRING_LB_GP_ONLINE_CASUAL_TIME_PLAYED_MAP_DUST2_NAME 417
#define SPASTRING_LB_GP_ONLINE_CASUAL_TIME_PLAYED_MAP_NUKE_NAME 418
#define SPASTRING_LB_GP_ONLINE_CASUAL_TIME_PLAYED_MAP_DUST_NAME 419
#define SPASTRING_LB_GP_ONLINE_CASUAL_TIME_PLAYED_MAP_AZTEC_NAME 420
#define SPASTRING_LB_WINS_ONLINE_CASUAL_NAME        424
#define SPASTRING_LB_WINS_ONLINE_GG_PROG_NAME       429
#define SPASTRING_LB_WINS_ONLINE_GG_BOMB_NAME       431
#define SPASTRING_LB_CS_ONLINE_CASUAL_NAME          435
#define SPASTRING_LB_CS_ONLINE_COMPETITIVE_NAME     436
#define SPASTRING_LB_CS_ONLINE_GG_PROG_NAME         440
#define SPASTRING_LB_CS_ONLINE_GG_BOMB_NAME         454
#define SPASTRING_LB_CS_ONLINE_GG_BOMB_AVG_CONTRIB_SCORE_NAME 455
#define SPASTRING_LB_CS_ONLINE_GG_BOMB_MVP_AWARDS_NAME 459
#define SPASTRING_LB_CS_ONLINE_GG_BOMB_TOTAL_ROUNDS_PLAYED_NAME 460
#define SPASTRING_LB_CS_ONLINE_GG_BOMB_TOTAL_CONTRIB_SCORE_NAME 461
#define SPASTRING_LB_CS_ONLINE_GG_BOMB_TOTAL_KILLS_NAME 462
#define SPASTRING_LB_CS_ONLINE_GG_BOMB_TOTAL_DEATHS_NAME 463
#define SPASTRING_LB_CS_ONLINE_GG_BOMB_TOTAL_DAMAGE_NAME 464
#define SPASTRING_LB_KD_ONLINE_CASUAL_NAME          501
#define SPASTRING_LB_KD_ONLINE_COMPETITIVE_NAME     503
#define SPASTRING_LB_KD_ONLINE_COMPETITIVE_KD_RANKED_NAME 504
#define SPASTRING_LB_KD_ONLINE_COMPETITIVE_TOTAL_KILLS_NAME 508
#define SPASTRING_LB_KD_ONLINE_GG_PROG_NAME         531
#define SPASTRING_LB_KD_ONLINE_GG_PROG_KD_RANKED_NAME 532
#define SPASTRING_LB_KD_ONLINE_GG_PROG_TOTAL_KILLS_NAME 536
#define SPASTRING_LB_KD_ONLINE_GG_BOMB_NAME         545
#define SPASTRING_LB_KD_ONLINE_GG_BOMB_KD_RANKED_NAME 546
#define SPASTRING_LB_KD_ONLINE_GG_BOMB_TOTAL_KILLS_NAME 550
#define SPASTRING_LB_STARS_ONLINE_CASUAL_NAME       572
#define SPASTRING_LB_STARS_ONLINE_COMPETITIVE_NAME  574
#define SPASTRING_LB_STARS_ONLINE_COMPETITIVE_TOTAL_STARS_NAME 575
#define SPASTRING_LB_STARS_ONLINE_COMPETITIVE_BOMBS_PLANTED_NAME 576
#define SPASTRING_LB_STARS_ONLINE_COMPETITIVE_BOMBS_DETONATED_NAME 577
#define SPASTRING_LB_STARS_ONLINE_COMPETITIVE_BOMBS_DEFUSED_NAME 578
#define SPASTRING_LB_STARS_ONLINE_COMPETITIVE_HOSTAGES_RESCUED_NAME 579
#define SPASTRING_LB_STARS_ONLINE_GG_PROG_NAME      609
#define SPASTRING_LB_STARS_ONLINE_GG_PROG_TOTAL_STARS_NAME 610
#define SPASTRING_LB_STARS_ONLINE_GG_PROG_BOMBS_PLANTED_NAME 611
#define SPASTRING_LB_STARS_ONLINE_GG_PROG_BOMBS_DETONATED_NAME 612
#define SPASTRING_LB_STARS_ONLINE_GG_PROG_BOMBS_DEFUSED_NAME 613
#define SPASTRING_LB_STARS_ONLINE_GG_PROG_HOSTAGES_RESCUED_NAME 614
#define SPASTRING_LB_STARS_ONLINE_GG_BOMB_NAME      623
#define SPASTRING_LB_STARS_ONLINE_GG_BOMB_TOTAL_STARS_NAME 624
#define SPASTRING_LB_STARS_ONLINE_GG_BOMB_BOMBS_PLANTED_NAME 625
#define SPASTRING_LB_STARS_ONLINE_GG_BOMB_BOMBS_DETONATED_NAME 626
#define SPASTRING_LB_STARS_ONLINE_GG_BOMB_BOMBS_DEFUSED_NAME 627
#define SPASTRING_LB_STARS_ONLINE_GG_BOMB_HOSTAGES_RESCUED_NAME 628
#define SPASTRING_LB_GP_ONLINE_CASUAL_NAME          650
#define SPASTRING_LB_GP_ONLINE_COMPETITIVE_NAME     652
#define SPASTRING_LB_GP_ONLINE_COMPETITIVE_GAMES_PLAYED_NAME 653
#define SPASTRING_LB_GP_ONLINE_COMPETITIVE_TIME_PLAYED_NAME 654
#define SPASTRING_LB_GP_ONLINE_COMPETITIVE_TOTAL_MEDALS_NAME 657
#define SPASTRING_LB_GP_ONLINE_COMPETITIVE_TIME_PLAYED_MAP_BANK_NAME 658
#define SPASTRING_LB_GP_ONLINE_COMPETITIVE_TIME_PLAYED_MAP_SHORTTRAIN_NAME 659
#define SPASTRING_LB_GP_ONLINE_COMPETITIVE_TIME_PLAYED_MAP_SHOOTS_NAME 660
#define SPASTRING_LB_GP_ONLINE_COMPETITIVE_TIME_PLAYED_MAP_STMARC_NAME 661
#define SPASTRING_LB_GP_ONLINE_COMPETITIVE_TIME_PLAYED_MAP_SUGARCANE_NAME 662
#define SPASTRING_LB_GP_ONLINE_COMPETITIVE_TIME_PLAYED_MAP_SAFEHOUSE_NAME 663
#define SPASTRING_LB_GP_ONLINE_COMPETITIVE_TIME_PLAYED_MAP_LAKE_NAME 664
#define SPASTRING_LB_GP_ONLINE_COMPETITIVE_TIME_PLAYED_MAP_BAGGAGE_NAME 665
#define SPASTRING_LB_GP_ONLINE_COMPETITIVE_TIME_PLAYED_MAP_INFERNO_NAME 666
#define SPASTRING_LB_GP_ONLINE_COMPETITIVE_TIME_PLAYED_MAP_ITALY_NAME 667
#define SPASTRING_LB_GP_ONLINE_COMPETITIVE_TIME_PLAYED_MAP_OFFICE_NAME 668
#define SPASTRING_LB_GP_ONLINE_COMPETITIVE_TIME_PLAYED_MAP_DUST2_NAME 669
#define SPASTRING_LB_GP_ONLINE_COMPETITIVE_TIME_PLAYED_MAP_NUKE_NAME 670
#define SPASTRING_LB_GP_ONLINE_COMPETITIVE_TIME_PLAYED_MAP_DUST_NAME 671
#define SPASTRING_LB_GP_ONLINE_COMPETITIVE_TIME_PLAYED_MAP_AZTEC_NAME 672
#define SPASTRING_LB_GP_ONLINE_GG_PROG_NAME         752
#define SPASTRING_LB_GP_ONLINE_GG_PROG_GAMES_PLAYED_NAME 753
#define SPASTRING_LB_GP_ONLINE_GG_PROG_TIME_PLAYED_NAME 754
#define SPASTRING_LB_GP_ONLINE_GG_PROG_TOTAL_MEDALS_NAME 757
#define SPASTRING_LB_GP_ONLINE_GG_PROG_TIME_PLAYED_MAP_BANK_NAME 758
#define SPASTRING_LB_GP_ONLINE_GG_PROG_TIME_PLAYED_MAP_SHORTTRAIN_NAME 759
#define SPASTRING_LB_GP_ONLINE_GG_PROG_TIME_PLAYED_MAP_SHOOTS_NAME 760
#define SPASTRING_LB_GP_ONLINE_GG_PROG_TIME_PLAYED_MAP_STMARC_NAME 761
#define SPASTRING_LB_GP_ONLINE_GG_PROG_TIME_PLAYED_MAP_SUGARCANE_NAME 762
#define SPASTRING_LB_GP_ONLINE_GG_PROG_TIME_PLAYED_MAP_SAFEHOUSE_NAME 763
#define SPASTRING_LB_GP_ONLINE_GG_PROG_TIME_PLAYED_MAP_LAKE_NAME 764
#define SPASTRING_LB_GP_ONLINE_GG_PROG_TIME_PLAYED_MAP_BAGGAGE_NAME 765
#define SPASTRING_LB_GP_ONLINE_GG_PROG_TIME_PLAYED_MAP_INFERNO_NAME 766
#define SPASTRING_LB_GP_ONLINE_GG_PROG_TIME_PLAYED_MAP_ITALY_NAME 767
#define SPASTRING_LB_GP_ONLINE_GG_PROG_TIME_PLAYED_MAP_OFFICE_NAME 768
#define SPASTRING_LB_GP_ONLINE_GG_PROG_TIME_PLAYED_MAP_DUST2_NAME 769
#define SPASTRING_LB_GP_ONLINE_GG_PROG_TIME_PLAYED_MAP_NUKE_NAME 770
#define SPASTRING_LB_GP_ONLINE_GG_PROG_TIME_PLAYED_MAP_DUST_NAME 771
#define SPASTRING_LB_GP_ONLINE_GG_PROG_TIME_PLAYED_MAP_AZTEC_NAME 772
#define SPASTRING_LB_GP_ONLINE_GG_BOMB_NAME         802
#define SPASTRING_LB_GP_ONLINE_GG_BOMB_GAMES_PLAYED_NAME 803
#define SPASTRING_LB_GP_ONLINE_GG_BOMB_TIME_PLAYED_NAME 804
#define SPASTRING_LB_GP_ONLINE_GG_BOMB_TOTAL_MEDALS_NAME 807
#define SPASTRING_LB_GP_ONLINE_GG_BOMB_TIME_PLAYED_MAP_BANK_NAME 808
#define SPASTRING_LB_GP_ONLINE_GG_BOMB_TIME_PLAYED_MAP_SHORTTRAIN_NAME 809
#define SPASTRING_LB_GP_ONLINE_GG_BOMB_TIME_PLAYED_MAP_SHOOTS_NAME 810
#define SPASTRING_LB_GP_ONLINE_GG_BOMB_TIME_PLAYED_MAP_STMARC_NAME 811
#define SPASTRING_LB_GP_ONLINE_GG_BOMB_TIME_PLAYED_MAP_SUGARCANE_NAME 812
#define SPASTRING_LB_GP_ONLINE_GG_BOMB_TIME_PLAYED_MAP_SAFEHOUSE_NAME 813
#define SPASTRING_LB_GP_ONLINE_GG_BOMB_TIME_PLAYED_MAP_LAKE_NAME 814
#define SPASTRING_LB_GP_ONLINE_GG_BOMB_TIME_PLAYED_MAP_BAGGAGE_NAME 815
#define SPASTRING_LB_GP_ONLINE_GG_BOMB_TIME_PLAYED_MAP_INFERNO_NAME 816
#define SPASTRING_LB_GP_ONLINE_GG_BOMB_TIME_PLAYED_MAP_ITALY_NAME 817
#define SPASTRING_LB_GP_ONLINE_GG_BOMB_TIME_PLAYED_MAP_OFFICE_NAME 818
#define SPASTRING_LB_GP_ONLINE_GG_BOMB_TIME_PLAYED_MAP_DUST2_NAME 819
#define SPASTRING_LB_GP_ONLINE_GG_BOMB_TIME_PLAYED_MAP_NUKE_NAME 820
#define SPASTRING_LB_GP_ONLINE_GG_BOMB_TIME_PLAYED_MAP_DUST_NAME 821
#define SPASTRING_LB_GP_ONLINE_GG_BOMB_TIME_PLAYED_MAP_AZTEC_NAME 822
#define SPASTRING_LB_WINS_WIN_AS_CT_NAME            926
#define SPASTRING_LB_WINS_WIN_AS_T_NAME             927
#define SPASTRING_PROPERTY_CSS_LB_KD_SHOTS_NAME     928
#define SPASTRING_PROPERTY_CSS_LB_KD_HEADSHOTS_NAME 929
#define SPASTRING_LB_KILL_DEATH_TOTAL_SHOTS_NAME    930
#define SPASTRING_LB_KILL_DEATH_TOTAL_HEADSHOTS_NAME 931
#define SPASTRING_PROPERTY_CSS_LB_GP_TIME_PLAYED_CT_NAME 932
#define SPASTRING_PROPERTY_CSS_LB_GP_TIME_PLAYED_T_NAME 933
#define SPASTRING_LB_GAMES_PLAYED_TIME_PLAYED_CT_NAME 934
#define SPASTRING_LB_GAMES_PLAYED_TIME_PLAYED_T_NAME 935
#define SPASTRING_PROPERTY_CSS_LB_KD_DEATHS_NAME    936
#define SPASTRING_LB_KILL_DEATH_TOTAL_DEATHS_NAME   937
#define SPASTRING_LB_KILL_DEATH_TOTAL_HITS_NAME     938
#define SPASTRING_PROPERTY_CSS_LB_KD_HITS_NAME      939
#define SPASTRING_CV_CSS_GAME_MODE_GUNGAMEPROGRESSIVE_NAME 940
#define SPASTRING_CV_CSS_GAME_MODE_GUNGAMEBOMB_NAME 942
#define SPASTRING_LB_WINS_LOSS_AS_CT_NAME           943
#define SPASTRING_LB_WINS_LOSS_AS_T_NAME            944
#define SPASTRING_PROPERTY_CSS_LB_WINS_LOSS_AS_CT_NAME 945
#define SPASTRING_PROPERTY_CSS_LB_WINS_LOSS_AS_T_NAME 946
#define SPASTRING_PROPERTY_CSS_SEARCH_LISTEN_SERVER_NAME 947
#define SPASTRING_CV_CSS_LEVEL_SHORTTRAIN_NAME      949
#define SPASTRING_PROPERTY_CSS_LB_CS_ELO_RATING_NAME 950
#define SPASTRING_LB_CONTRIBUTION_SCORE_ELO_RATING_NAME 951
#define SPASTRING_PROPERTY_CSS_MAX_OPEN_TEAM_SLOTS_NAME 952
#define SPASTRING_CT_CSS_MAP_GROUP_NAME             953
#define SPASTRING_CV_CSS_MAP_GROUP_BOMB_MG_NAME     954
#define SPASTRING_CV_CSS_MAP_GROUP_HOSTAGE_MG_NAME  955
#define SPASTRING_CV_CSS_MAP_GROUP_DEMOLITION_MG_NAME 956
#define SPASTRING_CV_CSS_MAP_GROUP_ARMSRACE_MG_NAME 957
#define SPASTRING_CV_CSS_MAP_GROUP_AZTEC_MG_NAME    958
#define SPASTRING_CV_CSS_MAP_GROUP_BAGGAGE_MG_NAME  959
#define SPASTRING_CV_CSS_MAP_GROUP_BANK_MG_NAME     960
#define SPASTRING_CV_CSS_MAP_GROUP_DUST_MG_NAME     961
#define SPASTRING_CV_CSS_MAP_GROUP_DUST2_MG_NAME    962
#define SPASTRING_CV_CSS_MAP_GROUP_INFERNO_MG_NAME  963
#define SPASTRING_CV_CSS_MAP_GROUP_ITALY_MG_NAME    964
#define SPASTRING_CV_CSS_MAP_GROUP_LAKE_MG_NAME     965
#define SPASTRING_CV_CSS_MAP_GROUP_NUKE_MG_NAME     966
#define SPASTRING_CV_CSS_MAP_GROUP_OFFICE_MG_NAME   967
#define SPASTRING_CV_CSS_MAP_GROUP_SAFEHOUSE_MG_NAME 968
#define SPASTRING_CV_CSS_MAP_GROUP_SHOOTS_MG_NAME   969
#define SPASTRING_CV_CSS_MAP_GROUP_SHORTTRAIN_MG_NAME 970
#define SPASTRING_CV_CSS_MAP_GROUP_STMARC_MG_NAME   971
#define SPASTRING_CV_CSS_MAP_GROUP_SUGARCANE_MG_NAME 972
#define SPASTRING_CV_CSS_MAP_GROUP_TRAIN_MG_NAME    973
#define SPASTRING_CV_CSS_MAP_GROUP_TRAINING_MG_NAME 974
#define SPASTRING_CV_CSS_LEVEL_TRAIN_NAME           975
#define SPASTRING_CV_CSS_LEVEL_TRAINING_NAME        976
#define SPASTRING_PRESENCE_LOBBY_NAME               979
#define SPASTRING_LB_GAMES_PLAYED_TIME_PLAYED_MAP_TRAIN_NAME 980
#define SPASTRING_PROPERTY_CSS_LB_GP_TIME_MAP_TRAIN_NAME 981
#define SPASTRING_PROPERTY_CSS_LB_GP_TIME_MAP_TRAINING_NAME 982
#define SPASTRING_LB_GAMES_PLAYED_TIME_PLAYED_MAP_TRAINING_NAME 983
#define SPASTRING_LB_ARCADE_WINS_ONLINE_CASUAL_RANK_COLUMN_NAME 985


#ifdef __cplusplus
}
#endif

#endif // __COUNTER_STRIKE__GO_SPA_H__


