//-----------------------------------------------------------------------------
// Autogenerated by schema compiler, compiled May 22 2009 14:03:37
// Do not hand-edit or check in this file!!
//-----------------------------------------------------------------------------

#ifndef PARTICLES_G_H
#define PARTICLES_G_H

#ifdef COMPILER_MSVC
#pragma once
#endif

#include "resourcefile/schema.h"


//-----------------------------------------------------------------------------
// Forward declarations
//-----------------------------------------------------------------------------
struct ParticleSystemDefinition_t;


//-----------------------------------------------------------------------------
// Structure definitions
//-----------------------------------------------------------------------------

//! dmeElementType = "DmeParticleSystemDefinition"
schema struct ParticleSystemDefinition_t
{
	int32            max_particles;
	int32            initial_particles;
	CResourceString  material;
	float32          cull_radius;
	CResourceArray< CResourceReference< ParticleSystemDefinition_t > > children;
};

DEFINE_RESOURCE_TYPE( ParticleSystemDefinition_t, RESOURCE_TYPE_PARTICLE_SYSTEM );
typedef const ResourceBinding_t< ParticleSystemDefinition_t > *HParticleSystem;
typedef CStrongHandle< ParticleSystemDefinition_t > HParticleSystemStrong;
#define PARTICLE_SYSTEM_HANDLE_INVALID ( (HParticleSystem)0 )


#endif // PARTICLES_G_H
