//  IMAGEBUILDER SHOULD MAKE A  LINE LIKE THIS WITH THE CHANGELIST NUMBER #DEFINED IN:
// IT'S OKAY IF IT BLOWS AWAY THE REST OF THIS FILE
// ONLY THIS ONE #define IS NECESSARY:

// #define APPCHANGELISTVERSION 936857




// IMAGEBUILDER SHOULD NOT EMIT THE FOLLOWING LINES
// THEY INDICATE THAT THIS IS *NOT* AN AUTOBUILT IMAGE
// AND SHOULD BE ABSENT FROM THE AUTOBUILDER'S LOCAL
// VERSION OF THIS .H


#define PS3CLVERMAJOR 0
#define PS3CLVERMINOR 1