//====== Copyright (C), Valve Corporation, All rights reserved. =======
//
// Purpose: This file defines all of our mapgroups that can be selected on
//			the client for GC-matchmaking and server would map these mapgroups
//			to the corresponding mapgroup of gamemodes.txt
//
//=============================================================================

MAPGROUPENUM( de_dust )
MAPGROUPENUM( de_dust2 )
MAPGROUPENUM( de_train )
MAPGROUPENUM( de_aztec )
MAPGROUPENUM( de_inferno )
MAPGROUPENUM( de_nuke )
MAPGROUPENUM( de_vertigo )
MAPGROUPENUM( de_mirage )

MAPGROUPENUM( cs_office )
MAPGROUPENUM( cs_italy )
MAPGROUPENUM( cs_assault )
MAPGROUPENUM( cs_militia )
MAPGROUPENUM( de_cache )

MAPGROUPENUM( de_overpass )
MAPGROUPENUM( de_cbble )
MAPGROUPENUM( de_canals )

MAPGROUPENUM( cs_cruise		)
MAPGROUPENUM( de_coast		)
MAPGROUPENUM( de_empire		)
MAPGROUPENUM( de_mikla		)
MAPGROUPENUM( de_royal		)
MAPGROUPENUM( de_santorini	)
MAPGROUPENUM( de_tulip		)
