//====== Copyright (C), Valve Corporation, All rights reserved. =======
//
// Purpose: This file defines all of our mapgroups that can be selected on
//			the client for GC-matchmaking and server would map these mapgroups
//			to the corresponding mapgroup of gamemodes.txt
//
//=============================================================================

MAPGROUPENUM( ar_shoots )
MAPGROUPENUM( ar_baggage )
MAPGROUPENUM( ar_monastery )
MAPGROUPENUM( de_lake )
MAPGROUPENUM( de_stmarc )
MAPGROUPENUM( de_safehouse )
