//====== Copyright (C), Valve Corporation, All rights reserved. =======
//
// Purpose: This file defines all of our mapgroups that can be selected on
//			the client for GC-matchmaking and server would map these mapgroups
//			to the corresponding mapgroup of gamemodes.txt
//
//=============================================================================

MAPGROUPENUM( active )
MAPGROUPENUM( dust247 )
MAPGROUPENUM( reserves )
MAPGROUPENUM( hostage )
MAPGROUPENUM( op_op07 )
