//====== Copyright (C), Valve Corporation, All rights reserved. =======
//
// Purpose: This file defines all of our mapgroups that can be selected on
//			the client for GC-matchmaking and server would map these mapgroups
//			to the corresponding mapgroup of gamemodes.txt
//
//=============================================================================

MAPGROUPENUM( de_bank )
MAPGROUPENUM( de_shorttrain )
MAPGROUPENUM( de_sugarcane )
MAPGROUPENUM( de_lake )
MAPGROUPENUM( de_stmarc )
MAPGROUPENUM( de_safehouse )
MAPGROUPENUM( de_shortdust )
