//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by hammer.rc
//
#define IDB_SPLASHOLD                   1
#define IDS_ERROR_PLAYING               1
#define IDD_ABOUTBOX                    100
#define IDC_PAKLISTFILES                101
#define IDC_PAKLISTDIREC                102
#define CG_IDD_PROGRESS                 103
#define CG_IDS_PROGRESS_CAPTION         104
#define IDC_FACEPAINT                   104
#define IDC_TEXTUREWINDOW               106
#define IDD_OBJPAGE_ENTITY              106
#define IDD_OBJPAGE_ENTITYKV            106
#define IDC_EDITPARAMETER               107
#define IDB_SPLASH1                     108
#define IDD_MAPEXPORT                   109
#define id_EditObjectInfo               110
#define id_EditObjectData               111
#define ID_2DTITLEWND                   112
#define ID_TOOLS_TRANSFORM              113
#define IDD_NEW                         113
#define IDC_X                           114
#define IDD_TRANSFORM                   114
#define IDC_Y                           115
#define ID_VSCALE_CHANGED               115
#define IDC_Z                           116
#define IDR_MAINFRAME                   128
#define IDR_FORGEMAPTYPE                129
#define IDR_MAPDOC                      129
#define IDR_MAPDOC_VALVE                129
#define IDR_FORGEPAKTYPE                130
#define IDR_QUAKEMAPTYPE                131
#define IDS_NONE                        131
#define IDR_FORGEMAPTYPE2               132
#define IDR_MANIFESTDOC                 132
#define IDD_BRUSH                       135
#define IDD_BRUSHEDITOR                 135
#define IDB_PAKENTRYTYPES               136
#define IDD_MAPVIEWBAR                  140
#define IDD_FILTERCONTROL               140
#define IDR_BRUSHEDITOR_MENU            144
#define IDD_TEXTURES                    145
#define IDD_ENTITY                      146
#define IDD_OBJPAGE_FLAGS               147
#define IDI_TEXTUREWINDOW               148
#define IDD_OBJPAGE_GROUPS              148
#define IDR_MAPEDITTOOLS                149
#define IDD_OBJPAGE_COMPLEX             149
#define IDI_BRUSHEDITOR                 152
#define IDD_COMPLEXOBJECTS              156
#define IDR_SELECTIONTOOLS              157
#define IDD_OBJPAGE_DUMMY               159
#define IDD_GROUPS                      160
#define IDD_OBJPAGE_TRANSFORMATIONS     161
#define BMB_SETTINGS                    162
#define IDD_OBJECTBAR                   162
#define BMI_SETTINGS                    164
#define IDR_2DMENU                      165
#define IDD_OBJPAGE_ENTITYSMART         170
#define IDD_TEXTUREBAR                  171
#define IDC_MAGNIFY                     171
#define IDB_SPLASH                      172
#define IDD_COPYRIGHT                   173
#define IDD_OPTIONS_MAIN                174
#define IDC_ENTITY                      174
#define IDD_MAPERRORS                   176
#define IDD_NEWKEYVALUE                 177
#define IDD_LAYERS                      178
#define IDR_MAPOPERATIONS               178
#define IDD_OPTIONS_EDITING             179
#define IDD_OPTIONS_2D                  179
#define IDR_POPUPS                      182
#define IDD_RUNMAP                      185
#define IDD_OPTIONS_QUAKE               186
#define IDD_SELECTEDBAR                 188
#define IDD_NEWCYLINDER                 189
#define IDD_FACEEDIT                    194
#define IDD_LOADINGTEXTURES             196
#define IDD_MAPINFO                     197
#define IDD_STRINPUT                    198
#define IDD_OPTIONS_3D                  199
#define IDD_WC_PASTESPECIAL             200
#define IDD_MAPCHECK                    202
#define IDD_UNDOWARNING                 203
#define IDD_DIALOG1                     204
#define IDD_PREFABS                     205
#define IDD_EDITPREFAB                  206
#define IDD_OPTIONS_CONFIGS             207
#define IDB_PREFABS                     208
#define IDD_TREETEST                    212
#define IDD_PASTESPECIAL1               214
#define IDD_RUNMAPEXPERT                215
#define IDD_RUNMAPCONFIGS               216
#define IDD_REPLACETEX                  217
#define IDC_CURSOR1                     218
#define IDC_HANDCURSOR                  219
#define IDC_HANDCLOSEDCURSOR            220
#define IDB_TREELISTCHECKS              223
#define IDD_EDITPATH                    224
#define IDD_EDITPATHNODE                230
#define IDD_SCALEVERTICES               233
#define IDD_ENTITYREPORT                234
#define IDB_TREEROOTS                   235
#define IDB_MAPEDITTOOLS                237
#define IDD_NEWDOCTYPE                  238
#define IDC_DECAL                       239
#define IDR_TOOLBAR1                    241
#define IDD_OBJPAGE_TIMELINE            243
#define IDC_NEWBOX                      244
#define IDC_CURSOR2                     245
#define IDC_NEXT_SOUND                  245
#define IDD_OPTIONS_TEXTURES            246
#define IDD_ARCH                        247
#define IDD_SELECTENTITY                248
#define IDR_MAPEDITTOOLS_NOTVALVE       257
#define IDR_MAPEDITTOOLS_VALVE          258
#define IDR_MAPOPERATIONS_NOTVALVE      259
#define IDR_MAPOPERATIONS_VALVE         260
#define IDR_MAPDOC_NOTVALVE             266
#define IDD_FIZZLEHUCK                  269
#define IDD_EDITGAMECONFIGS             272
#define IDD_OPTIONS_BUILD               275
#define IDB_MAPEDITTOOLS_256            284
#define IDD_GOTO_BRUSH                  286
#define IDD_ANIMATIONDLG                287
#define IDB_GIZMO_AXIS                  289
#define IDB_GIZMO_TRANSLATE_HANDLE      290
#define IDB_GIZMO_SCALE_HANDLE          291
#define IDB_GIZMO_ROTATE_HANDLE         292
#define IDR_DISPEDIT_TOOLBAR            293
#define IDD_DISP_GENERATE               295
#define IDD_DISP_IMPORT                 297
#define IDD_DISP_ELEVATE                299
#define IDD_OBJPAGE_OUTPUT              300
#define IDD_EDIT_CONNECTION             301
#define IDD_DISP_ALPHADLG               302
#define IDD_FACEEDIT_DISP               303
#define IDD_ENTITY_HELP                 304
#define IDD_OBJPAGE_INPUT               306
#define IDD_DISP_CREATE                 307
#define IDD_DISP_NOISE                  308
#define IDD_DISP_PAINT_DIST             309
#define IDD_DISP_PAINT_DATA             310
#define IDI_INPUTBAD                    311
#define IDI_INPUT                       312
#define IDC_EYEDROPPER                  312
#define IDI_OUTPUTBAD                   313
#define IDI_OUTPUT                      314
#define IDD_SEARCH_REPLACE              314
#define IDD_SELECT_MODE_BAR             315
#define IDD_OBJPAGE_MODEL               316
#define IDI_EYEDROPPER                  317
#define IDD_SMOOTHING_GROUPS            318
#define IDD_SMOOTHING_GROUP_VISUAL      319
#define IDI_MOVE_UP                     320
#define IDD_TORUS                       320
#define IDI_MOVE_DOWN                   321
#define IDD_NEW_VISGROUP                322
#define IDI_CROSSHAIR                   323
#define IDD_SOUNDBROWSER                323
#define IDC_CROSSHAIR                   324
#define IDB_VISGROUP_TREE_BUTTONS       325
#define IDR_UNDOREDO                    326
#define IDD_FILESYSTEM_OPENDIALOG       327
#define IDB_LABEL_MDL                   328
#define IDB_LABEL_FOLDER                329
#define IDB_BITMAP1                     330
#define IDB_LABEL_FILE                  331
#define IDD_MODEL_BROWSER               332
#define IDD_DIFFMAP                     333
#define IDD_CHECKMAP                    333
#define IDI_ICON1                       334
#define IDI_CAMERA                      334
#define IDD_SAVEDIALOG                  337
#define IDD_SCENE_PREVIEW               338
#define IDD_EDIT_INSTANCE               339
#define IDD_MANIFEST                    339
#define IDB_MANIFEST                    340
#define IDD_DIALOG2                     341
#define IDR_MANIFEST                    342
#define IDD_MANIFEST_MOVE               343
#define IDD_MANAGE_LIST_DIALOG          344
#define IDD_FADE_DIALOG                 345
#define IDD_PARTICLE_BROWSER            346
#define IDD_MANIFEST_CONTROL            347
#define IDB_MANIFEST_ICONS              348
#define IDR_MANIFEST_FILTER             349
#define IDD_MANIFEST_MAP                350
#define IDD_DISP_PAINT_SCULPT           351
#define IDD_DISP_SCULPT_PUSH_OPTIONS    352
#define IDD_DISP_SCULPT_PROJECT_OPTIONS 353
#define IDD_DISP_SCULPT_CARVE_OPTIONS   354
#define IDD_MANIFEST_CHECKIN            355
#define IDI_ICON2                       356
#define IDI_OUTPUT_EXTERNAL             356
#define IDD_ENTITY_SPRINKLE             357
#define IDD_DIALOG_SYNC_FILE            358
#define IDD_DIALOG_WITH_CHECKBOX        359
#define IDR_BLEND_ACCELERATOR           360
#define IDC_BRDLG_FLIPHORIZ             1000
#define IDC_BRDLG_FLIPVERT              1001
#define CG_IDC_PROGDLG_PROGRESS         1003
#define CG_IDC_PROGDLG_PERCENT          1004
#define IDC_MVBAR_ZOOM                  1004
#define IDC_MVBOX_EDITLAYERS            1006
#define IDC_EDITLAYERS                  1006
#define IDC_COMBO1                      1007
#define IDC_LAYERS                      1007
#define IDC_CREATELIST                  1007
#define IDC_TEXTURES                    1007
#define IDC_GDFILE                      1007
#define IDC_ITEMCOLOR                   1007
#define IDC_LIBRARIES                   1007
#define IDC_CREATEIN                    1007
#define IDC_GRID                        1007
#define IDC_FILTERCLASS                 1007
#define IDC_DEFAULTPOINT                1007
#define IDC_EDIT_CONN_OUTPUT            1007
#define IDC_KEYWORDS                    1007
#define ID_DISP_BRUSHSIZE               1007
#define ID_DISP_PAINTTYPE               1007
#define ID_DISP_PAINT_DIST_BRUSH        1007
#define ID_DISP_PAINT_DATA_BRUSH        1007
#define IDC_SEQUENCE                    1007
#define IDC_SPIN1                       1008
#define IDC_NUMSIDES_SPIN               1008
#define IDC_FACESSPIN                   1008
#define IDC_SPIN                        1008
#define IDC_SPINSHIFTX                  1008
#define IDC_UNDOSPIN                    1008
#define IDC_SCALESPIN                   1008
#define IDC_FROMHOURSPIN                1008
#define IDC_WALLWIDTHSPIN               1008
#define IDC_DEFAULTENTITY               1008
#define ID_SPIN_DISP_POWER              1008
#define ID_DISP_CREATE_POWER_SPIN       1008
#define ID_DISP_NOISE_MIN_SPIN          1008
#define IDC_EDIT1                       1009
#define IDC_NAME                        1009
#define IDC_CUSTOMLAYER                 1009
#define IDC_KEY                         1009
#define IDC_MAPFILES                    1009
#define IDC_WINDOWCOLOR                 1009
#define IDC_QUAKEDIR                    1009
#define IDC_NUMSIDES                    1009
#define IDC_SCALEX                      1009
#define IDC_FACES                       1009
#define IDC_EDIT                        1009
#define IDC_DESCRIPTION                 1009
#define IDC_OBJECTNOTES                 1009
#define IDC_TOHOURSPIN                  1009
#define IDC_GAME                        1009
#define IDC_BRUSH_NUMBER                1009
#define IDC_EDIT_DISP_SCALE             1009
#define IDC_EDIT_DISP_ELEVATE           1009
#define IDC_EDIT_CONN_DELAY             1009
#define IDC_CORDON_TEXTURE              1009
#define IDC_EDIT_ALPHA1                 1009
#define ID_DISP_ALPHA0                  1009
#define ID_DISP_SCALE                   1009
#define ID_DISP_CREATE_POWER            1009
#define ID_DISP_NOISE_MIN               1009
#define ID_DISP_PAINT_DATA_EDIT_VALUE   1009
#define IDC_FIND_TEXT                   1009
#define ID_EDIT_SMOOTHING_ANGLE         1009
#define IDC_VISGROUP_NAME               1009
#define IDC_SOUNDNAME_SELECTED          1009
#define IDC_FILENAME                    1009
#define IDC_SAVETIME                    1009
#define IDC_PASTE_SPECIAL_PREFIX        1009
#define IDC_PASTE_SPECIAL_PREFIX_TEXT   1009
#define IDC_MAPNAME                     1009
#define IDC_MANIFEST_FRIENDLY_NAME      1009
#define IDC_SCULPT_PUSH_OPTION_OFFSET_DISTANCE 1009
#define IDC_EDITBOX                     1009
#define IDC_CHECKIN_DESCRIPTION         1009
#define IDC_SPRINKLE_GRID_OFFSET_X      1009
#define IDC_BUTTON1                     1010
#define IDC_CONTROLHEIGHT               1010
#define IDC_EDITCLASSCODE               1010
#define IDC_SIZEPLANEDATA               1010
#define IDC_EDITCOMPLEXOBJECTS          1010
#define IDC_EDITSCRIPT                  1010
#define IDC_TMOVEUP                     1010
#define IDC_FILTER_LAYERS               1010
#define IDC_EDITDEFAULTS                1010
#define IDC_BROWSE                      1010
#define IDC_TEXTUREFILES                1010
#define IDC_CATEGORYLIST                1010
#define IDC_FROMMINUTESPIN              1010
#define IDC_GAMEDIR                     1010
#define ID_SMOOTHING_APPLY              1010
#define ID_SG_VISUAL_1                  1010
#define ID_DISP_INVERT_ALPHA            1010
#define IDC_UP_BUTTON                   1010
#define IDC_EDIT5                       1010
#define IDC_AUTOSAVESPACE               1010
#define IDC_LOAD_IMAGE                  1010
#define IDC_BUTTON_FADE_LOW             1010
#define IDC_SPRINKLE_GRID_SIZE_X        1010
#define IDC_TEXTURE_BUTTON1             1010
#define IDC_REVERT                      1011
#define IDC_TMOVEDOWN                   1011
#define IDC_FILTER_GROUPS               1011
#define IDC_MAPDIR                      1011
#define IDC_TOMINUTESPIN                1011
#define IDC_BSP                         1011
#define IDC_SPIN_LIGHTMAP_SCALE         1011
#define IDC_VISGROUP_MOVEDOWN           1011
#define IDC_LOOKIN                      1011
#define IDC_MAPITERATIONS               1011
#define IDC_SCULPT_PUSH_OPTION_OFFSET_AMOUNT 1011
#define IDC_TEXTURE_BUTTON2             1011
#define IDC_VISGROUP_MOVEUP             1012
#define IDC_TDELETE                     1012
#define IDC_BROWSE_BSP                  1012
#define IDC_GAMEDIR2                    1012
#define IDC_MODDIR                      1012
#define ID_SG_VISUAL_2                  1012
#define IDC_UNDOSPIN2                   1012
#define IDC_SCULPT_PUSH_OPTION_SMOOTH_AMOUNT 1012
#define IDC_TEXTURE_BUTTON3             1012
#define IDC_TNEW                        1013
#define IDC_PARMS_BSP                   1013
#define ID_SG_VISUAL_3                  1013
#define IDC_SCULPT_PUSH_OPTION_FALLOFF_POSITION 1013
#define IDC_PREFABDIR                   1013
#define IDC_SOLIDWINDOW                 1014
#define IDC_BROWSE_LIGHT                1014
#define ID_SG_VISUAL_4                  1014
#define IDC_TEXTURE_BUTTON4             1014
#define IDC_APPLY                       1015
#define IDC_SOLIDWINDOW2                1015
#define IDC_PARMS_LIGHT                 1015
#define ID_FACEEDIT_APPLY               1015
#define ID_SG_VISUAL_5                  1015
#define IDC_SCULPT_PUSH_OPTION_SMOOTH_AMOUNT3 1015
#define IDC_SCULPT_PUSH_OPTION_FALLOFF_FINAL 1015
#define IDC_BROWSE_VIS                  1016
#define ID_SG_VISUAL_6                  1016
#define IDC_PARMS_VIS                   1017
#define ID_SG_VISUAL_7                  1017
#define IDC_BROWSE_BSPDIR               1018
#define ID_SG_VISUAL_8                  1018
#define ID_SG_VISUAL_9                  1019
#define ID_SG_VISUAL_10                 1020
#define ID_SG_VISUAL_11                 1021
#define ID_SG_VISUAL_12                 1022
#define IDC_ROTATE                      1023
#define ID_SG_VISUAL_13                 1023
#define IDC_KEYVALUES                   1024
#define ID_SG_VISUAL_14                 1024
#define ID_SG_VISUAL_15                 1025
#define ID_SG_VISUAL_16                 1026
#define IDC_TEXTURESIZE                 1027
#define ID_SG_VISUAL_17                 1027
#define IDC_BROWSERDUMMY                1028
#define ID_SG_VISUAL_18                 1028
#define ID_SG_VISUAL_19                 1029
#define IDC_CLASS                       1030
#define ID_SG_VISUAL_20                 1030
#define ID_SG_VISUAL_21                 1031
#define IDC_DELETEKEYVALUE              1032
#define IDC_REMOVEKEYVALUE              1032
#define ID_SG_VISUAL_22                 1032
#define IDC_ADDKEYVALUE                 1033
#define ID_SG_VISUAL_23                 1033
#define IDC_EDITKEY                     1034
#define ID_SG_VISUAL_24                 1034
#define IDC_EDITVALUE                   1035
#define ID_SG_VISUAL_25                 1035
#define IDC_FLAG9                       1036
#define ID_SG_VISUAL_26                 1036
#define IDC_FLAG8                       1037
#define ID_SG_VISUAL_27                 1037
#define IDC_NOTHARD                     1038
#define IDC_FLAG12                      1038
#define ID_SG_VISUAL_28                 1038
#define IDC_NOTDEATHMATCH               1039
#define IDC_FLAG13                      1039
#define ID_SG_VISUAL_29                 1039
#define IDC_FLAG4                       1040
#define ID_SG_VISUAL_30                 1040
#define IDC_FLAG5                       1041
#define IDC_ANGLE_90                    1041
#define ID_SG_VISUAL_31                 1041
#define IDC_FLAG6                       1042
#define IDC_ANGLE_135                   1042
#define ID_SG_VISUAL_32                 1042
#define IDC_FLAG7                       1043
#define IDC_ANGLE_180                   1043
#define IDC_FLAG0                       1044
#define IDC_ANGLE_225                   1044
#define IDC_FLAG1                       1045
#define IDC_ANGLE_270                   1045
#define IDC_FLAG2                       1046
#define IDC_ANGLE_315                   1046
#define IDC_FLAG3                       1047
#define IDC_ANGLE_0                     1047
#define IDC_ANGLE_45                    1048
#define IDC_FLAG10                      1048
#define IDC_FLAG11                      1049
#define IDC_FLAG14                      1050
#define IDC_TEXTURENAME                 1051
#define IDC_FLAG15                      1051
#define IDC_TEXTUREANGLE                1052
#define IDC_HORZFLIP                    1053
#define IDC_VERTFLIP                    1054
#define IDC_VIEWPLANEDATA               1055
#define IDC_VERTSCALE_EDIT              1059
#define IDC_VERTSCALE                   1060
#define IDC_FLAG16                      1060
#define IDC_HORZSCALE                   1061
#define IDC_FLAG17                      1061
#define IDC_HORZSCALE_EDIT              1062
#define IDC_FLAG18                      1062
#define IDC_VERTSHIFT                   1063
#define IDC_FLAG19                      1063
#define IDC_VERTSHIFT_EDIT              1064
#define IDC_FLAG20                      1064
#define IDC_HORZSHIFT                   1065
#define IDC_FLAG21                      1065
#define IDC_HORZSHIFT_EDIT              1066
#define IDC_FLAG22                      1066
#define IDC_COPYTOALL                   1067
#define IDC_FLAG23                      1067
#define IDC_XANGLE                      1073
#define IDC_YANGLE                      1074
#define IDC_ZANGLE                      1075
#define IDC_XLOCK                       1076
#define IDC_YLOCK                       1077
#define IDC_GROUPLIST                   1077
#define IDC_ZLOCK                       1078
#define IDC_PARAMETERS                  1079
#define IDC_BUILD                       1080
#define IDC_PREVIEW                     1082
#define IDC_OPEN_SOURCE                 1083
#define IDC_IMPORT                      1084
#define IDC_REMOVE                      1085
#define IDC_AUTHOR                      1086
#define IDC_COMMENTS                    1087
#define IDC_CLASSLIST                   1088
#define IDC_EDITGROUPS                  1091
#define IDC_NOTVIS3D_INVISIBLE          1092
#define IDC_NEW                         1093
#define IDC_NOTVIS3D_WIREFRAME          1093
#define IDC_COLOR                       1094
#define IDC_COLORBOX                    1095
#define IDC_GROUPLIST1                  1096
#define IDC_GROUPS                      1097
#define ID_MATERIALEXCLUDE_LIST         1098
#define IDC_CHECKLIST                   1098
#define IDC_FILE_LIST                   1098
#define IDC_GROUPS2                     1098
#define IDC_SCRIPT_LIST                 1098
#define IDC_CUSTLAYERSLIDER             1099
#define IDC_LIST_DISP_INTERVAL          1100
#define IDC_TTYPE                       1101
#define IDC_HARDEN                      1102
#define IDC_CLEAR                       1103
#define IDC_CORDONS                     1104
#define IDC_ANGLEBOX                    1105
#define IDC_VALUE                       1106
#define IDC_ANGLEEDIT                   1107
#define IDC_SMART_ANGLEEDIT             1108
#define IDC_TEXTUREPIC                  1109
#define IDC_SMART_ANGLEBOX              1109
#define ID_EDIT_TOENTITY                1110
#define IDC_BROWSE1                     1111
#define IDC_BROWSE2                     1112
#define IDC_WACKY                       1112
#define IDC_BROWSEMAPFILES              1112
#define IDC_BROWSEMAPS                  1112
#define IDC_WINDOWS                     1113
#define IDC_BROWSETEXTUREFILE           1113
#define IDC_ITEMS                       1114
#define IDC_KVLISTCAPTION               1116
#define IDC_SMARTEDIT                   1119
#define IDC_VIEW                        1120
#define IDC_PLAY_SOUND                  1121
#define IDC_ERRORS                      1122
#define IDC_INCLUSIVE                   1124
#define IDC_EDIT2                       1125
#define IDC_EDIT3                       1126
#define IDC_TOMINUTE                    1127
#define IDC_MAKEDEFAULT                 1128
#define IDC_TEXTUREFILE                 1131
#define IDC_LIGHT                       1132
#define IDC_VIS                         1133
#define IDC_RADIO2                      1134
#define IDC_RADIO3                      1135
#define IDC_QBSP                        1137
#define IDC_BSP0                        1137
#define IDC_NOQUAKE                     1138
#define IDC_NOGAME                      1138
#define IDC_WAITFORKEYPRESS             1139
#define IDC_CLASSPROMPT                 1140
#define IDC_LIGHT2                      1140
#define IDC_RAD1                        1140
#define IDC_WAHH                        1141
#define IDC_LIGHT3                      1141
#define IDC_EXTRA                       1141
#define IDC_RAD2                        1141
#define IDC_SAVEVISIBLES                1142
#define IDC_SAVEVISIBLESONLY            1142
#define IDC_SHIFTY                      1144
#define IDC_SHIFTX                      1149
#define IDC_SCALEY                      1150
#define IDC_ADDTEXFILE                  1151
#define IDC_REMOVETEXFILE               1152
#define IDC_ADDTEXFILE2                 1153
#define IDC_CROSSHAIRS                  1154
#define IDC_GROUPCARVE                  1156
#define IDC_TEXTUREGROUPS               1158
#define IDC_BRIGHTNESS                  1159
#define IDC_BROWSEQUAKE                 1160
#define IDC_QUAKEPARMS                  1161
#define IDC_ROTATECONSTRAIN             1163
#define IDC_SOLIDS                      1164
#define IDC_POINTENTITIES               1165
#define IDC_SCROLLBARS                  1165
#define IDC_SOLIDENTITIES               1166
#define IDC_DRAWVERTICES                1166
#define IDC_DRAWMODELSIN2D              1167
#define IDC_QBSP2                       1169
#define IDC_BSP1                        1169
#define IDC_QBSP3                       1170
#define IDC_PROMPT                      1170
#define IDC_BSP2                        1170
#define IDC_HARDWARE                    1171
#define IDC_COPIES                      1172
#define IDC_OFFSETX                     1173
#define IDC_OFFSETY                     1174
#define IDC_OFFSETZ                     1175
#define IDC_GETOFFSETX                  1176
#define IDC_GETOFFSETY                  1177
#define IDC_GETOFFSETZ                  1178
#define IDC_GROUP                       1179
#define IDC_ROTATEX                     1180
#define IDC_ROTATEY                     1181
#define IDC_ROTATEZ                     1182
#define IDC_CENTERORIGINAL              1183
#define IDC_SPINSHIFTY                  1184
#define IDC_SPINROTATE                  1185
#define IDC_GO                          1187
#define IDC_UNDO                        1189
#define IDC_NOSHOW                      1190
#define IDC_MAX_CAMERAS                 1190
#define IDC_RADIO1                      1192
#define IDC_METHOD                      1192
#define IDC_INMARKED                    1192
#define IDC_LOOP                        1192
#define IDC_FILTERBYTYPE                1192
#define IDC_NEWTYPE                     1192
#define ID_DISP_SELECTION               1192
#define ID_DISP_PAINT_DIST_RAISELOWER   1192
#define ID_DISP_PAINT_DATA_RAISELOWER   1192
#define IDC_PLACE_IN_EXISTING_VISGROUP  1192
#define IDC_RADIO5                      1194
#define IDC_OBJECTS                     1194
#define IDC_ADDOBJECT                   1195
#define IDC_ADDLIBRARY                  1196
#define IDC_REMOVEOBJECT                1197
#define IDC_EDITOBJECT                  1199
#define IDC_LIBRARYNOTES                1202
#define IDC_REMOVELIBRARY               1203
#define IDC_EDITLIBRARY                 1204
#define IDC_DESCRIPT                    1204
#define IDC_EXPORTOBJECT                1205
#define IDC_ORDER                       1206
#define IDC_CREATEINPROMPT              1207
#define IDC_REMOVECONFIGURATION         1208
#define IDC_DATAFILES                   1209
#define IDC_DATAFILE_ADD                1210
#define IDC_GDFILE_ADD                  1210
#define IDC_DATAFILE_REMOVE             1211
#define IDC_GDFILE_REMOVE               1211
#define IDC_CONFIGURATIONS              1212
#define IDC_NEWCONFIGURATION            1213
#define IDC_EDITCONFIGURATION           1214
#define IDC_BUTTON6                     1215
#define IDC_GDFILE_EDIT                 1215
#define IDC_CAMERA_DISTANCE             1215
#define IDC_MAPBROWSE                   1215
#define IDC_SELECT_ADJACENT             1215
#define IDC_DEGREES                     1216
#define IDC_SHOWORDERFORM               1217
#define ID_INSERTPREFAB_ORIGINAL        1219
#define IDC_REVERSEY                    1221
#define IDC_EXTRACT                     1224
#define IDC_WHITEONBLACK                1225
#define IDC_EXPERT                      1226
#define IDC_NORMAL                      1227
#define IDC_MOVEUP                      1237
#define IDC_BROWSECOMMAND               1238
#define IDC_COMMAND                     1239
#define IDC_COMMANDLIST                 1240
#define IDC_MOVEDOWN                    1241
#define IDC_INSERTPARM                  1243
#define IDC_LONGFILENAMES               1244
#define IDC_ENSURECHECK                 1245
#define IDC_ENSUREFN                    1246
#define IDC_EDITCONFIGS                 1247
#define IDC_RENAME                      1249
#define IDC_FINDPIC                     1250
#define IDC_REPLACEPIC                  1251
#define IDC_INEVERYTHING                1253
#define IDC_BROWSEREPLACE               1254
#define IDC_BROWSEFIND                  1255
#define IDC_FIND                        1256
#define IDC_REPLACE                     1257
#define IDC_RADIO4                      1259
#define IDC_ACTION                      1260
#define IDC_VISIBLEONLY                 1261
#define IDC_USEPROCESSWND               1262
#define IDC_COPY                        1263
#define IDC_SIZEPROMPT                  1265
#define IDC_FILTERPROMPT                1266
#define IDC_CURNAME                     1267
#define IDC_SOUNDNAME                   1267
#define IDC_CURDESCRIPTION              1268
#define IDC_SOUNDNAME2                  1268
#define IDC_FILTER                      1269
#define IDC_SOUNDNAME3                  1269
#define IDC_GRIDHIGH10                  1270
#define IDC_HIDESMALLGRID               1271
#define IDC_MODE                        1274
#define IDC_GRIDINTENSITY               1275
#define IDC_FIX                         1277
#define IDC_FACESPROMPT                 1278
#define IDC_FIXALL                      1278
#define IDC_RANDOMYAW                   1278
#define IDC_NUDGE                       1281
#define IDC_ORIENTPRIMITIVES            1282
#define IDC_AUTOSELECT                  1283
#define IDC_BACKPLANE                   1283
#define IDC_BACKTEXT                    1284
#define IDC_SELECTBYHANDLES             1285
#define IDC_MARKONLY                    1288
#define IDC_USED                        1289
#define IDC_RESCALETEXTURECOORDINATES   1289
#define IDC_GRIDHIGHSPEC                1290
#define IDC_HIDEMASK                    1294
#define IDC_KEEPCLONEGROUP              1295
#define IDC_SPEED                       1297
#define IDC_RETRIGGER                   1298
#define IDC_YAWSPEED                    1299
#define IDC_PCWAIT                      1300
#define IDC_SCALE                       1301
#define IDC_MARK_AND_ADD                1302
#define IDC_MARK                        1303
#define IDC_GOTO                        1304
#define IDC_TEXTURES_RELOAD             1304
#define IDC_DELETE                      1305
#define IDC_TEXTURES_OPEN_SOURCE        1305
#define IDC_FILTERBYKEYVALUE            1306
#define IDC_FILTERKEY                   1308
#define IDC_FILTERVALUE                 1309
#define IDC_FILTERBYHIDDEN              1310
#define IDC_PROPERTIES                  1311
#define IDC_ENTITIES                    1318
#define IDC_FILTERBYCLASS               1319
#define IDC_EXACTVALUE                  1320
#define IDC_GRIDHIGH64                  1321
#define IDC_GRIDDOTS                    1322
#define IDC_MARKMEMBERS                 1323
#define IDC_PURGEVISGROUPS              1324
#define IDC_SMOOTHSPIN                  1325
#define IDC_SMOOTH                      1326
#define IDC_MATERIAL                    1327
#define IDC_CENTERONCAMERA              1331
#define IDC_REDHERRING                  1332
#define IDC_FROMHOUR                    1333
#define IDC_TOHOUR                      1334
#define IDC_FROMMINUTE                  1335
#define IDC_ACTIVATE                    1337
#define IDC_LOADWINPOSITIONS            1338
#define IDC_INDEPENDENTWINDOWS          1339
#define IDC_WALLWIDTH                   1340
#define IDC_SIDESSPIN                   1341
#define IDC_ARC                         1342
#define IDC_ARCSPIN                     1343
#define IDC_SIDES                       1344
#define IDC_CIRCLE                      1345
#define IDC_ANGLE                       1346
#define IDC_ANGLESPIN                   1347
#define IDC_ARCH_PREVIEW                1348
#define IDC_ROTATION_SIDES              1348
#define IDC_ADDHEIGHT                   1349
#define IDC_HIDDEN                      1350
#define IDC_ROTATION_ARC                1350
#define IDC_USEGROUPCOLORS              1351
#define IDC_CROSS_SECTION_RADIUS        1351
#define IDC_PASTE                       1354
#define IDC_SPINSCALEX                  1355
#define IDC_SPINSCALEY                  1356
#define IDC_FIZZLEHUCK                  1356
#define IDC_EXPAND                      1358
#define IDC_Q2_LIGHT                    1359
#define IDC_Q2_SLICK                    1360
#define IDC_Q2_SKY                      1361
#define IDC_Q2_WARP                     1362
#define IDC_Q2_TRANS33                  1363
#define IDC_Q2_TRANS66                  1364
#define IDC_Q2_FLOWING                  1365
#define IDC_Q2_NODRAW                   1366
#define IDC_Q2_SOLID                    1367
#define IDC_Q2_WINDOW                   1368
#define IDC_Q2_AUX                      1369
#define IDC_Q2_LAVA                     1370
#define IDC_Q2_SLIME                    1371
#define IDC_Q2_WATER                    1372
#define IDC_Q2_MIST                     1373
#define IDC_Q2_CURRENT90                1374
#define IDC_Q2_CURRENT180               1375
#define IDC_Q2_CURRENT270               1376
#define IDC_Q2_CURRENTUP                1377
#define IDC_Q2_CURRENTDN                1378
#define IDC_Q2_ORIGIN                   1379
#define IDC_Q2_MONSTER                  1380
#define IDC_Q2_CORPSE                   1381
#define IDC_Q2_DETAIL                   1382
#define IDC_Q2_TRANSLUCENT              1383
#define IDC_Q2_LADDER                   1384
#define IDC_Q2_PLAYERCLIP               1385
#define IDC_Q2_MONSTERCLIP              1386
#define IDC_Q2_CURRENT0                 1387
#define IDC_MEASURE_EXPAND              1388
#define IDC_Q2_VALUE                    1389
#define IDC_LIGHTMAP_SCALE              1389
#define IDC_MEASURE_BASE                1390
#define IDC_ADD                         1390
#define IDC_CONFIGS                     1391
#define IDC_Q2_HINT                     1391
#define IDC_Q2_SPLITTER                 1392
#define IDC_BROWSEPALETTE               1394
#define IDC_TEXTUREFORMAT               1395
#define IDC_MAPFORMAT                   1396
#define IDC_PICKCOLOR                   1396
#define IDC_BROWSEMAPDIR                1397
#define IDC_BROWSE_GAME                 1398
#define IDC_BROWSEGAMEDIR               1398
#define IDC_BROWSEPREFABDIR             1398
#define IDC_PARMS_GAME                  1399
#define IDC_BROWSEMODDIR                1399
#define IDC_BSPDIR                      1400
#define IDC_GROUPWHILEIGNOREGROUPS      1401
#define IDC_STRETCH_ARCH                1402
#define IDC_USEMOUSELOOK                1402
#define IDC_JUSTIFY_TOPLEFT             1403
#define IDC_JUSTIFY_TOP                 1403
#define IDC_VGUI_MODELBROWSER           1403
#define IDC_JUSTIFY_LEFT                1404
#define IDC_ENABLE_PERFORCE_INTEGRATION 1404
#define IDC_JUSTIFY_CENTER              1405
#define IDC_JUSTIFY_FITTOFACE           1406
#define IDC_JUSTIFY_RIGHT               1407
#define IDC_ALIGN_WORLD                 1408
#define IDC_ALIGN_FACE                  1409
#define IDC_TREAT_AS_ONE                1410
#define IDC_JUSTIFY_BOTTOM              1411
#define IDC_DETAIL_DISTANCE             1412
#define IDC_DETAIL_DISTANCE_TEXT        1413
#define IDC_MODEL_DISTANCE              1414
#define IDC_MODEL_DISTANCE_TEXT         1415
#define IDC_ANIMATE_MODELS              1416
#define IDC_ENTITY_NUMBER               1417
#define IDC_SEARCH_VISIBLE_BRUSHES_ONLY 1418
#define IDC_UNIQUETEXTURES              1419
#define IDC_TEXTUREMEMORY               1420
#define IDC_WADSUSED                    1421
#define IDC_FORWARD_SPEED               1424
#define IDC_FORWARD_ACCELERATION        1425
#define IDC_FORWARD_SPEED_TEXT          1426
#define IDC_FORWARD_ACCEL_TEXT          1427
#define IDC_TIMESLIDER                  1428
#define IDC_LIST                        1428
#define IDC_ANIMATIONPLAY               1429
#define IDC_EDIT_CONN_TARGET            1429
#define IDC_EDIT_CONN_INPUT             1430
#define IDC_ANIMATIONCREATEKEYFRAME     1431
#define IDC_EDIT_CONN_PARAMETER         1431
#define IDC_EDIT_CONN_PARAM             1431
#define IDC_CONTENTS_AREAPORTAL         1440
#define IDC_CONTENTS_PLAYERCLIP         1441
#define IDC_CONTENTS_MONSTERCLIP        1442
#define IDC_CONTENTS_DETAIL             1443
#define IDC_CONTENTS_TRANSLUCENT        1444
#define IDC_CONTENTS_ORIGIN             1445
#define IDC_CONTENTS_LADDER             1446
#define IDC_SURF_NODRAW                 1447
#define IDC_SURF_HINT                   1448
#define IDC_SURF_SKIP                   1449
#define IDC_EDIT4                       1450
#define IDC_EDIT_ALPHA4                 1450
#define ID_DISP_ALPHA3                  1450
#define ID_NOISE_MAX                    1450
#define ID_DISP_PAINT_DIST_EDIT_RADIUS  1450
#define IDC_BUILD_NUMBER                1451
#define IDC_FILTER_TEXTURES             1452
#define IDC_GAMEEXEDIR                  1453
#define IDC_BROWSEGAMEEXEDIR            1454
#define IDC_VIS0                        1455
#define IDC_VIS1                        1456
#define IDC_VIS2                        1457
#define IDC_RAD0                        1458
#define IDC_REVERSE_SELECTION           1460
#define IDC_MODEL_DISTANCE_STATIC       1461
#define IDC_DETAIL_DISTANCE_STATIC      1464
#define IDC_GRIDHIGH1024                1465
#define IDC_BROWSE_CORDON_TEXTURE       1466
#define IDC_DEFAULT_TEXTURE_SCALE       1467
#define IDC_DEFAULT_LIGHTMAP_SCALE      1468
#define IDC_SHOW_ALL                    1470
#define IDC_EDIT_ALPHA2                 1472
#define IDC_EDIT_ALPHA3                 1473
#define ID_DISP_CREATE                  1474
#define ID_DISP_APPLY                   1475
#define ID_DISP_DESTROY                 1476
#define ID_DISP_POWER                   1478
#define ID_DISP_ELEVATION               1480
#define ID_DISP_ALPHA1                  1482
#define ID_DISP_ALPHA2                  1483
#define ID_SPIN_DISP_ELEVATION          1486
#define IDC_KEYWORDS_TEXT               1487
#define ID_DISP_BRUSHHGT                1488
#define ID_DISP_SELECT                  1489
#define ID_DISP_MASK_SELECT             1489
#define ID_DISP_GRID                    1490
#define ID_DISP_MASK_GRID               1490
#define ID_SPIN_DISP_HEIGHT             1492
#define IDC_EDIT_CONN_FIRE_ONCE         1493
#define IDC_ENTITY_COMMENTS             1494
#define ID_DISP_SUBDIVIDE               1495
#define ID_DISP_SEW                     1496
#define IDC_ENTITY_HELP                 1497
#define IDC_HELP_TEXT                   1499
#define ID_DISP_PAINT_ALPHA             1500
#define ID_DISP_PAINT                   1500
#define ID_ALPHA_LAYER_3                1501
#define ID_ALPHA_LAYER_0                1502
#define ID_ALPHA_LAYER_1                1503
#define ID_ALPHA_LAYER_2                1504
#define ID_DISP_SMOOTH_ALPHA            1505
#define ID_NOISE_ADD                    1507
#define ID_NOISE_MIN                    1509
#define ID_NOISE_ROCKY                  1510
#define ID_SLIDER_DISP_VALUE            1512
#define ID_DISP_VALUE                   1513
#define ID_COMBO_DISP_BRUSHES           1515
#define BrushGroup                      1518
#define ID_CHANNEL_DISTANCE             1519
#define ID_CHANNEL_ALPHA                1520
#define ID_DISP_AUTOSEW                 1521
#define ID_MATERIALEXCLUDE_ADD          1522
#define ID_MATERIALEXCLUDE_REM          1523
#define IDC_KEYVALUE_HELP               1524
#define IDC_KEYVALUE_HELP_GROUP         1525
#define IDC_FILTER_OPAQUE               1528
#define IDC_FILTER_TRANSLUCENT          1529
#define IDC_FILTER_SELFILLUM            1530
#define IDC_FILTER_ENVMASK              1531
#define IDC_SHOW_ERROR                  1532
#define IDC_PICK_FACES                  1533
#define IDC_PICK_ENTITY                 1534
#define IDC_PICK_ANGLES                 1535
#define IDC_PICK_ENTITY_PARAM           1535
#define ID_DISP_NOISE_MAX_SPIN          1538
#define ID_DISP_NOISE_MAX               1539
#define ID_DISP_PAINT_DIST_RAISETO      1541
#define ID_DISP_PAINT_DIST_SMOOTH       1542
#define ID_DISP_PAINT_DIST_AUTOSEW      1543
#define ID_DISP_PAINT_DIST_SLIDER_DISTANCE 1544
#define ID_DISP_PAINT_DIST_AXIS         1545
#define ID_DISP_PAINT_DIST_SLIDER_RADIUS 1547
#define ID_DISP_PAINT_DIST_SPATIAL      1548
#define ID_DISP_PAINT_DIST_EDIT_DISTANCE 1550
#define ID_DISP_SELECT2                 1552
#define ID_DISP_NOISE                   1557
#define ID_DISP_PAINT_GEO               1558
#define ID_DISP_PAINT_DATA              1559
#define ID_DISP_PAINT_DATA_RAISETO      1560
#define ID_DISP_SCULPT_PAINT            1560
#define ID_DISP_PAINT_DATA_SMOOTH       1561
#define ID_DISP_PAINT_DATA_SLIDER_VALUE 1562
#define ID_DISP_PAINT_DATA_TYPE         1564
#define ID_MAP_ENABLELIGHTPREVIEW       1565
#define IDC_VISIBLES_ONLY               1565
#define ID_MAP_DISABLELIGHTPREVIEW      1566
#define IDC_FIND_NEXT                   1566
#define ID_MAP_UPDATELIGHTPREVIEW       1567
#define IDC_REPLACE_ALL                 1567
#define ID_MAP_ABORTLIGHTCALCULATION    1568
#define IDC_REPLACE_TEXT                1568
#define IDC_SELECTION                   1570
#define IDC_ENTIRE_FILE                 1571
#define IDC_NAMES_ONLY                  1572
#define IDC_WHOLE_WORD                  1573
#define IDC_CASE_SENSITIVE              1574
#define IDC_FRAME_SCROLLBAR             1575
#define IDC_FRAME_TEXT                  1576
#define ID_DISP_TAG_WALK                1580
#define ID_DISP_TAG_BUILD               1581
#define ID_BUTTON_SMOOTHING_GROUPS      1582
#define ID_SMOOTHING_GROUP_1            1583
#define ID_BUTTON_SHIFTX_RANDOM         1583
#define ID_DISPPAINT_SOFTEDGE           1584
#define ID_BUTTON_SHIFTY_RANDOM         1584
#define ID_DISPPAINT_HARDEDGE           1585
#define IDC_TORUS_PREVIEW               1586
#define IDC_ROTATION_ANGLE              1587
#define IDC_PREVIEW_TOP_VIEW            1588
#define IDC_TORUS_COMPUTE_RADIUS        1589
#define IDC_CHECK_VISIBLE_ONLY          1589
#define ID_SMOOTHING_GROUP_2            1602
#define ID_SMOOTHING_GROUP_3            1603
#define ID_SMOOTHING_GROUP_4            1604
#define ID_SMOOTHING_GROUP_5            1605
#define ID_SMOOTHING_GROUP_6            1606
#define ID_SMOOTHING_GROUP_7            1607
#define ID_SMOOTHING_GROUP_8            1608
#define ID_SMOOTHING_GROUP_9            1609
#define ID_SMOOTHING_GROUP_10           1610
#define ID_SMOOTHING_GROUP_11           1611
#define ID_SMOOTHING_GROUP_12           1612
#define ID_SMOOTHING_GROUP_13           1613
#define ID_SMOOTHING_GROUP_14           1614
#define ID_SMOOTHING_GROUP_15           1615
#define ID_SMOOTHING_GROUP_16           1616
#define ID_SMOOTHING_GROUP_17           1617
#define ID_SMOOTHING_GROUP_18           1618
#define ID_SMOOTHING_GROUP_19           1619
#define ID_SMOOTHING_GROUP_20           1620
#define ID_SMOOTHING_GROUP_21           1621
#define ID_SMOOTHING_GROUP_22           1622
#define ID_SMOOTHING_GROUP_23           1623
#define ID_SMOOTHING_GROUP_24           1624
#define ID_SMOOTHING_GROUP_25           1625
#define ID_SMOOTHING_GROUP_26           1626
#define ID_SMOOTHING_GROUP_27           1627
#define ID_SMOOTHING_GROUP_28           1628
#define ID_SMOOTHING_GROUP_29           1629
#define ID_SMOOTHING_GROUP_30           1630
#define ID_SMOOTHING_GROUP_31           1631
#define ID_SMOOTHING_GROUP_32           1632
#define IDC_REMOVE_FROM_ALL             1633
#define IDC_GROUP_LIST                  1634
#define IDC_SOUND_FILTER                1635
#define IDC_HIDE_OBJECTS                1635
#define IDC_SOUND_TYPE                  1636
#define IDC_SOUND_LIST                  1640
#define IDC_AUTOPLAY                    1641
#define IDC_SOUND_FILE                  1642
#define IDC_SOUND_SOURCE_FILE           1643
#define IDC_CREATE_NEW_VISGROUP         1643
#define IDC_FILENAME_LABEL              1644
#define IDC_TAB1                        1645
#define IDC_PASTE_SPECIAL_MAKE_UNIQUE   1646
#define IDC_PASTE_SPECIAL_ADD_PREFIX    1647
#define IDC_CHECK1                      1648
#define IDC_RAD_HDR                     1648
#define ID_DISP_NOHULL_COLL             1648
#define IDC_SHOWHIDDENTARGETS           1648
#define IDC_MANIFEST_CENTER_AROUND_BRUSH 1648
#define IDC_MANIFEST_PRIMARY            1648
#define IDC_DO_OPERATION                1648
#define IDC_SCULPT_PUSH                 1648
#define IDC_TEXTURE1_MASK               1648
#define IDC_SIMILARCHECK                1649
#define IDC_AUTOSAVEDIR                 1649
#define IDC_SCULPT_CARVE                1649
#define IDC_TEXTURE2_MASK               1649
#define IDC_BROWSEAUTOSAVEDIR           1650
#define IDC_SCULPT_BLEND                1650
#define IDC_TEXTURE3_MASK               1650
#define IDC_ENABLEAUTOSAVE              1651
#define IDC_TEXTURE4_MASK               1651
#define IDC_AUTOSAVETIMELABEL           1652
#define IDC_COLOR1_MASK                 1652
#define IDC_AUTOSAVESPACELABEL          1653
#define IDC_COLOR2_MASK                 1653
#define IDC_AUTOSAVEITERATIONLABEL      1654
#define IDC_COLOR3_MASK                 1654
#define IDC_AUTOSAVEDIRECTORYLABEL      1655
#define IDC_TEXTURE4_MASK2              1655
#define IDC_COLOR4_MASK                 1655
#define ID_DISP_NOPHYSICS_COLL          1656
#define IDC_CHECK3                      1657
#define ID_DISP_NORAY_COLL              1657
#define IDC_SPRINKLE_DEFINITION_GRID_SIZE 1657
#define IDC_SCULPT_BLEND_OPTION_DRAW_COLOR 1657
#define IDC_FOV                         1659
#define IDC_STOPSOUND                   1661
#define IDC_SCRIPT_LIST_EDIT            1661
#define IDC_SAVING_TEXT                 1662
#define IDC_KEY_LABEL                   1663
#define IDC_VALUE_LABEL                 1664
#define IDC_REFRESH_SOUNDS              1665
#define IDC_SCENE_NAME                  1666
#define IDC_CURRENT_SOUND               1667
#define IDC_ANGLES_LABEL                1668
#define IDC_COMMENTS_LABEL              1669
#define IDC_OUTPUTS_STATIC_PANEL        1670
#define IDC_OUTPUT_LABEL                1671
#define IDC_TARGETS_LABEL               1672
#define IDC_VIA_INPUT_LABEL             1673
#define IDC_PARAMETER_LABEL             1674
#define IDC_DELAY_LABEL                 1675
#define IDC_INFO_TEXT                   1676
#define IDC_MANIFEST_LIST               1677
#define IDC_MANIFEST_FILENAME           1678
#define IDC_MANIFEST_NAME2              1679
#define IDC_MANIFEST_FULL_FILENAME      1679
#define IDC_BUTTON3                     1679
#define IDC_BLEND_COLOR_OPERATION       1679
#define IDC_BUTTON_FADE_MED             1680
#define IDC_BUTTON2                     1681
#define IDC_SET_COLOR                   1681
#define IDC_TEXTURES_EXPLORE_SOURCE     1681
#define IDC_BUTTON_FADE_HIGH            1682
#define IDC_SET_COLOR2                  1682
#define IDC_BUTTON_FADE_360             1683
#define IDC_BUTTON_FADE_LEVEL           1684
#define IDC_FACE_MARK_BUTTON            1684
#define IDC_SPRINKLE_USE_GRID           1684
#define IDC_SCRIPT_LIST_REMOVE          1685
#define IDC_BROWSE_INSTANCE             1686
#define IDC_SCRIPT_LIST_ADD             1686
#define IDC_FULL_PATH                   1687
#define IDC_SCRIPT_LIST_ADD2            1687
#define IDC_MODELS_USED                 1688
#define IDC_LIST1                       1689
#define IDC_CURRENT_FILTERS             1690
#define IDC_AVAILABLE_FILTERS           1691
#define IDC_SCULPT_PUSH_OPTION_OFFSET_MODE 1691
#define IDC_HEATMAP_INSERT              1692
#define IDC_SCULPT_PUSH_OPTION_DENSITY_MODE 1692
#define IDC_HEATMAP_NEW                 1693
#define IDC_IDC_SCULPT_PUSH_OPTION_OFFSET_MODE 1693
#define IDC_HEATMAP_REMOVE              1694
#define IDC_IDC_SCULPT_PUSH_OPTION_NORMAL_MODE 1694
#define IDC_HEATMAP_GENERATE            1695
#define IDC_SCULPT_OPTIONS_LOC          1695
#define IDC_LOG_FILE_LIST               1696
#define IDC_SCULPT_PROJECT              1696
#define IDC_ADD_LOG                     1697
#define IDC_PROJECT_SIZE                1697
#define IDC_REMOVE_LOG                  1698
#define IDC_PROJECT_SIZE_NUM            1698
#define IDD_HEATMAPS                    1699
#define IDC_CARVE_BRUSH                 1699
#define IDC_HEATMAP_FILTERS             1700
#define IDC_CHECKIN_LIST                1701
#define IDC_CHECKIN_STATUS              1702
#define IDC_SPRINKLE_DENSITY            1703
#define IDC_SPRINKLE_MODE               1704
#define IDC_SPRINKLE_GRID_OFFSET_Y      1705
#define IDC_SPRINKLE_GRID_SIZE_Y        1706
#define IDC_SPRINKLE_TYPE               1707
#define IDC_SPRINKLE_DENSITY_DISPLAY    1708
#define IDC_SPRINKLE_RANDOM_YAW         1709
#define IDSYNC                          1711
#define IDC_STATUS_TEXT                 1712
#define IDCHECKOUT2                     1713
#define IDREVERT                        1714
#define IDC_REVISION                    1715
#define IDC_SYNC_ICON                   1716
#define IDC_DIALOG_ICON                 1717
#define IDD_MAPDOC_CHECKIN              1723
#define IDD_MAPDOC_STATUS               1724
#define IDCHECKOUT                      1725
#define IDD_DISP_SCULPT_BLEND_OPTIONS   1725
#define IDADD                           1726
#define ID_SUBMIT                       1727
#define IDC_BLEND_AMOUNT                1728
#define IDC_SCULPT_BLEND_OPTION_DRAW_MODE 1729
#define IDC_BLEND_AMOUNT_TEXT           1730
#define IDC_COLOR_BLEND_AMOUNT          1731
#define IDC_BSP_CHECKMARK_TEXT          1731
#define IDC_CHECKMARK_CONTROL           1731
#define IDC_DIALOG_TEXT                 1732
#define IDC_ALPHA_BLEND_AMOUNT_TEXT     1732
#define IDC_ALPHA_BLEND_AMOUNT          1733
#define IDC_CHECKMARK_TEXT              1734
#define IDC_SCULPT_BLEND_OPTION_DRAW_TEXTURE 1734
#define IDC_SCULPT_BLEND_OPTION_DRAW_ALPHA 1735
#define IDC_COLOR_BLEND_AMOUNT_TEXT     1736
#define IDI_OUTPUT_GREY                 31235
#define IDI_OUTPUTBAD_GREY              31236
#define IDI_INPUT_GREY                  31237
#define IDI_INPUTBAD_GREY               31238
#define ID_PAK_DELENTRY                 32772
#define ID_BUTTON32773                  32773
#define ID_PAK_ADDENTRY                 32774
#define ID_VIEW_3DTEXTURED              32777
#define ID_VIEW_3DWIREFRAME             32778
#define ID_VIEW_2DXY                    32779
#define ID_VIEW_2DXZ                    32780
#define ID_VIEW_2DYZ                    32781
#define ID_BUTTON32782                  32782
#define IDS_CANT_OPEN_ENTS_FILE         32782
#define IDS_CANT_SAVE_ENTS_FILE         32783
#define ID_NO_BRUSH_SELECTED            32784
#define ID_VIEW_3DFILLEDPOLYGONS        32785
#define ID_BRUSH_NUMBER                 32786
#define ID_BRUSH_NOT_FOUND              32787
#define ID_VIEW_3DTEXTURED_SHADED       32788
#define ID_VIEW_3DPOLYGON               32790
#define ID_VIEW_GRID                    32796
#define ID_BUTTON32799                  32799
#define ID_BUTTON32800                  32800
#define ID_VIEW_BRUSHEDITOR             32801
#define IDBE_VIEW_WIREFRAME             32804
#define IDBE_VIEW_POLYGON               32805
#define IDBE_VIEW_TEXTURED              32806
#define IDBE_VIEW_ROTATE                32807
#define ID_VIEW_TEXTUREBROWSER          32808
#define ID_TOOLS_SIMPLEOBJECT           32809
#define ID_TOOLS_COMPLEXOBJECT          32810
#define ID_TOOLS_BLOCK                  32812
#define ID_TOOLS_POINTER                32813
#define ID_TOOLS_ENTITY                 32816
#define ID_VIEW_PROPERTIES              32818
#define ID_EDIT_PROPERTIES              32819
#define ID_VIEW_MESSAGES                32820
#define ID_HELP_BRUSHEDITOR             32822
#define ID_VIEW_4VIEWS                  32823
#define ID_VIEW_AUTOSIZE4               32824
#define ID_TOOLS_MANIPULATE             32827
#define ID_TOOLS_MAGNIFY                32829
#define ID_TOOLS_CAMERA                 32833
#define ID_SELECTION_ROTATE             32836
#define ID_SELECTION_MOVE               32837
#define ID_SELECTION_SHEAR              32838
#define ID_SELECTION_SIZE               32841
#define ID_SELECTION_ALIGNRIGHT         32842
#define ID_SELECTION_ALIGNLEFT          32843
#define ID_SELECTION_ALIGNBOTTOM        32844
#define ID_SELECTION_ALIGNTOP           32845
#define ID_OPTIONS_SELECTIONBAR         32847
#define ID_CREATEBOX                    32849
#define ID__3DSYNC                      32850
#define ID_3DSYNC                       32851
#define ID__SNAPTOGRID                  32853
#define ID_TOGGLE_SNAPTOGRID            32854
#define ID_TOGGLE_GRID                  32855
#define ID__REVERSEATTRIBUTES           32856
#define ID_TOGGLE_REVERSEATTRIBUTES     32857
#define ID_EDIT_DELETE                  32858
#define ID_MAP_SNAPTOGRID               32863
#define ID_EDIT_CLEARSELECTION          32865
#define ID_EDIT_APPLYTEXTURE            32867
#define ID_TOOLS_SUBTRACTSELECTION      32868
#define ID_TOOLS_OPTIONS                32870
#define ID_TOOLS_GROUP                  32871
#define ID_TOOLS_UNGROUP                32872
#define ID_EDIT_TOWORLD                 32873
#define ID_EDIT_SELECTALL               32875
#define ID_EDIT_LAYERS                  32878
#define ID_MAP_GRIDLOWER                32879
#define ID_MAP_GRIDHIGHER               32880
#define ID_VIEW_MAXIMIZEPANE            32888
#define ID_VIEW_MAXIMIZERESTOREACTIVEVIEW 32889
#define ID_TOOLS_ALIGNLEFT              32891
#define ID_TOOLS_ALIGNRIGHT             32892
#define ID_TOOLS_ALIGNTOP               32893
#define ID_TOOLS_ALIGNBOTTOM            32894
#define ID_CREATEOBJECT                 32899
#define ID_FILE_EXPORT                  32900
#define ID_EDIT_MAPPROPERTIES           32902
#define ID_FILE_RUNMAP                  32903
#define ID_TOOLS_SHOWITEMS              32906
#define ID_TOOLS_HIDEITEMS              32907
#define ID_VIEW3D_BRIGHTER              32909
#define ID_VIEW3D_DARKER                32910
#define ID_MODE_APPLICATOR              32913
#define ID_TOOLS_VERTEX                 32915
#define ID_MAP_INFORMATION              32916
#define ID_TOOLS_LOADPTSFILE            32917
#define ID_VIEW_CENTERONSELECTION       32918
#define ID_TOOLS_HOLLOWOUT              32919
#define ID_TOOLS_HOLLOW                 32920
#define ID_EDIT_PASTESPECIAL            32921
#define ID_EDIT_SELNEXT                 32923
#define ID_EDIT_SELPREV                 32924
#define ID_VIEW_HIDESELECTEDOBJECTS     32925
#define ID_EDIT_SELNEXT_CASCADING       32926
#define ID_EDIT_SELPREV_CASCADING       32927
#define ID_MAP_CHECK                    32930
#define ID_VIEW_SHOWCONNECTIONS         32931
#define ID_TOOLS_PREFABFACTORY          32932
#define ID_TOOLS_CREATEPREFAB           32933
#define ID_VIEW_DOTACAMERA              32934
#define ID_FLIP_HORIZONTAL              32935
#define ID_FLIP_VERTICAL                32936
#define ID_TEST                         32937
#define ID_EDIT_PASTEWC                 32938
#define ID_HELP_FIRST_TIME_SETUP        32939
#define ID_HELP_TOPICS                  32940
#define ID_EDIT_CUTWC                   32941
#define ID_EDIT_COPYWC                  32942
#define ID_HELP_WEBSITE                 32943
#define ID_HELP_EDITINGSITE             32944
#define ID_HELP_ORDERNOW                32945
#define ID_EDIT_REPLACETEX              32946
#define ID_TOOLS_SNAPSELECTEDTOGRID     32947
#define ID_EDIT_UNDOREDOACTIVE          32949
#define ID_TOOLS_MORPH                  32952
#define ID_TOOLS_SPLITFACE              32954
#define ID_TOOLS_CLIPPER                32955
#define ID_TOOLS_TOGGLETEXLOCK          32956
#define ID_TOGGLE_CORDON                32960
#define ID_EDIT_CORDON                  32961
#define ID_TOOLS_EDITCORDON             32962
#define ID_TOOLS_NEWCORDON              32963
#define ID_VIEW_HIDENONSELECTEDOBJECTS  32964
#define ID_TOGGLE_GROUPIGNORE           32965
#define ID_TOOLS_PATH                   32966
#define ID__IDPATHEDITDELETE            32989
#define ID_PATHEDIT_DELETE              32990
#define ID__ADD                         32991
#define ID_PATHEDIT_ADD                 32992
#define ID_PATHEDIT_NODEPROPERTIES      32993
#define ID_PATHEDIT_PATHPROPERTIES      32994
#define ID_VSCALE_TOGGLE                -32541
#define ID_MAP_ENTITYREPORT             32996
#define ID_TOGGLE_SELECTBYHANDLE        32999
#define ID_TOGGLE_INFINITESELECT        33000
#define ID_FILE_EXPORTTODXF             33001
#define ID_WINDOW_TOGGLE                33002
#define ID_TOOLS_APPLYDECALS            33008
#define ID_SAVEWINDOWSTATE              33009
#define ID_LOADWINDOWSTATE              33010
#define ID_PATHEDIT_DELETEPATH          33011
#define ID_MAP_LOADPOINTFILE            33021
#define ID_MAP_UNLOADPOINTFILE          33022
#define ID_PATHEDIT_SELECTPATH          33023
#define ID_PATHEDIT_HIDEPATH            33024
#define ID_FILE_EXPORTAGAIN             33025
#define ID_HELP_ENTITYGUIDE             33026
#define ID_FACE_JUSTIFYTEXTURE_LEFT     33027
#define ID_FACE_JUSTIFYTEXTURE_RIGHT    33028
#define ID_FACE_JUSTIFYTEXTURE_CENTER   33029
#define ID_FACE_JUSTIFYTEXTURE_NONE     33030
#define ID_FACE_JUSTIFYTEXTURE_FITTOFACE 33032
#define ID_FACE_ALIGNTEXTURE_TOFACE     33034
#define ID_FACE_ALIGNTEXTURE_TOWORLD    33035
#define ID_FACE_JUSTIFYTEXTURE_TOPLEFT  33036
#define ID_FACE_JUSTIFYTEXTURE_TOP      33036
#define ID_TOOLS_TEXTUREALIGN           33045
#define ID_FACE_JUSTIFYTEXTURE_BOTTOM   33051
#define ID_TOGGLE_3D_GRID               33059
#define ID_GOTO_BRUSH                   33061
#define ID_TOOLS_DISPLACE               33063
#define ID_DISP_LOAD                    33064
#define ID_DISP_SAVE                    33065
#define ID_DISP_IMPORT                  33066
#define ID_DISP_GENERATE                33067
#define ID_DISP_UNDO                    33068
#define ID_DISP_RAISELOWER              33069
#define ID_DISP_FLATTEN                 33070
#define ID_DISP_SMOOTH                  33071
#define ID_DISP_BRUSHSIZE_1             33072
#define ID_DISP_BRUSHSIZE_3             33073
#define ID_DISP_BRUSHSIZE_5             33074
#define ID_DISP_BRUSHSIZE_7             33075
#define ID_DISP_BRUSHSIZE_9             33076
#define ID_DISP_HEIGHT_1                33077
#define ID_DISP_HEIGHT_2                33078
#define ID_DISP_HEIGHT_4                33079
#define ID_DISP_HEIGHT_6                33080
#define ID_DISP_HEIGHT_16               33081
#define ID_DISP_HEIGHT_32               33082
#define ID_DISP_HEIGHT_8                33083
#define ID_DISP_DELETE                  33084
#define ID_DISP_MASK                    33085
#define ID_DISP_EXPORT                  33086
#define ID_DISP_PULLPUSH                33087
#define ID_HELP_WORLDCRAFT_SUPPORT_MAIL 33093
#define ID_DISP_ELEVATE                 33094
#define ID_VIEW_3DLIGHTMAP_GRID         33095
#define ID_DISP_ALPHA                   33097
#define ID_MAP_UNITS_NONE               33099
#define ID_MAP_UNITS_INCHES             33100
#define ID_MAP_UNITS_FEET_INCHES        33101
#define ID_TOOLS_HIDE_ENTITY_NAMES      33102
#define ID_VIEW_OPAQUE_MATERIALS        33103
#define ID_FILE_CONVERT_WAD             33104
#define ID_BUTTON_DISP_DRAW             33105
#define ID_TOOLS_DISP_SOLIDDRAW         33106
#define ID_TOOLS_OVERLAY                33107
#define ID_ENABLE_LIGHT_PREVIEW_CUSTOM_FILENAME 33108
#define ID_VIEW_LIGHTINGPREVIEW         33109
#define ID_MAP_TOGGLELIGHTPREVIEW       33110
#define ID_VIEW_LIGHTINGPREVIEW_RAYTRACED 33111
#define ID_EDIT_FINDENTITIES            33113
#define ID_VIEW_SHOW_HELPERS            33114
#define ID_TOOLS_DISP_DRAW3D            33116
#define ID_TOOLS_DISP_DRAWWALKABLE      33117
#define ID_TOOLS_DISP_DRAWBUILDABLE     33118
#define ID_VIEW_3DSMOOTH                33119
#define ID_MAP_ENTITY_GALLERY           33171
#define ID_VIEW_CENTER3DVIEWSONSELECTION 33172
#define DISP_DRAWREMOVEDVERTS           33173
#define ID_TOOLS_DISP_DRAWREMOVEDVERTS  33174
#define ID_SHOW_SELECTED_BRUSH_NUMBER   33175
#define ID_GOTO_COORDS                  33176
#define ID_TOOLS_SOUND_BROWSER          33177
#define ID_TOOLS_MODEL_BROWSER          33178
#define ID_FILE_RELOAD_SOUNDS           33179
#define ID_CENTER_ON_ENTITY             33181
#define ID_TOOLS_CENTER_ORIGINS         33182
#define ID_TOOLS_SNAP_SELECTED_TO_GRID_INDIVIDUALLY 33183
#define ID_VIEW_SHOWMODELSIN2D          33198
#define ID_VIEW_PREVIEW_MODEL_FADE      33202
#define ID_MAP_DIFFMAPFILE              33203
#define ID_VIEW_2DLOGICAL               33205
#define ID_Menu                         33207
#define ID_LOGICALVIEWSETTINGS_HIDEORPHANENTITIES 33208
#define ID_VIEW_LOGICAL_GRID            33209
#define ID_LOGICALOBJECT_MOVETOGETHER   33210
#define ID_LOGICALOBJECT_SELECTCASCADING 33212
#define ID_LOGICALOBJECT_SELECTALLCASCADING 33213
#define ID_VIEW_HIDEUNCONNECTED         33214
#define ID_LOGICALOBJECT_SELECTALLCONNECTED 33215
#define ID_TOOLS_TOGGLETEXLOCKSCALE     33216
#define ID_UNDO                         33217
#define ID_REDO                         33218
#define ID_LOGICALOBJECT_LAYOUTGEOMETRIC 33219
#define ID_LOGICALOBJECT_LAYOUTLOGICAL  33220
#define ID_LOGICALOBJECT_LAYOUTDEFAULT  33221
#define ID_COLLISION_WIREFRAME          33223
#define ID_SHOW_DETAIL_OBJECTS          33224
#define ID_MAP_LOADPORTALFILE           33225
#define ID_SHOW_NODRAW_BRUSHES          33226
#define ID_VIEW_INSTANCES               33226
#define ID_MAP_UNLOADPORTALFILE         33227
#define ID_INSTANCES_SHOWTINTED         33228
#define ID_INSTANCES_SHOWNORMAL         33229
#define ID_TOOLS_INSTANCES_HIDE         33230
#define ID_TOOLS_INSTANCES_SHOWTINTED   33231
#define ID_TOOLS_INSTANCES_SHOWNORMAL   33232
#define ID_TOOLS_MANIFEST               33233
#define ID_Menu33234                    33234
#define ID_FILE_MANIFEST                33235
#define ID_BUTTON33236                  33236
#define ID_BUTTON33237                  33237
#define ID_BUTTON33238                  33238
#define ID_MANIFEST_MOVESELECTIONTONEWSUBMAP 33239
#define ID_MANIFEST_FILE_MOVESELECTIONTONEWSUBMAP 33240
#define ID_FILE_IMPORTFUNC              33241
#define ID_FILE_IMPORT_FUNC_INSTANCES   33242
#define ID_SCREENELEMENTS_MANIFESTBAR   33243
#define ID_MOVESELECTIONTO_SUBMAP       33246
#define ID_MOVESELECTIONTO_NEWSUBMAP    33247
#define ID_VERSIONCONTROL_CHECKOUT      33248
#define ID_INSTANCING_CREATEMANIFEST    33250
#define ID_INSTANCING_VERSIONCONTROL    33251
#define ID_VERSIONCONTROL_CHECKINALL    33252
#define ID_VERSIONCONTROL_CHECKOUTALL   33253
#define ID_INSTANCING_VIEWMANIFESTS     33254
#define ID_VIEWMANIFESTS_HIDEEXCEPTCURRENT 33255
#define ID_VIEWMANIFESTS_TINTED         33256
#define ID_VIEWMANIFESTS_SHOWNORMAL     33257
#define ID_VERSIONCONTROL_CHECKIN       33258
#define ID_INSTANCING_WINDOWS           33259
#define ID_WINDOWS_HIDEALLINSTANCES     33260
#define ID_WINDOWS_SHOWALLINSTANCES     33261
#define ID_INSTANCES_HIDEALL            33262
#define ID_INSTANCES_SHOWALL            33263
#define ID_PRIMARY_INSERT               33264
#define ID_INSERT_EMPTYSUBMAP           33265
#define ID_INSERT_EXISTINGSUBMAP        33266
#define ID_FOUNDRY_SENDSELECTEDENTITIESTOENGINE 33267
#define ID_FOUNDRY_MOVEENGINEVIEWTOHAMMER3DVIEW 33268
#define ID_FOUNDRY_REMOVESELECTEDENTITIESFROMENGINE 33269
#define ID_FOUNDRY_MOVEFOCUSTOENGINE    33270
#define ID_ACCELERATOR33240             33271
#define ID_VERSIONCONTROL_CHECKIN33267  33272
#define ID_Menu33268                    33273
#define ID_INSTANCES_COLLAPSE           33274
#define ID_INSTANCES_COLLAPSEALL        33275
#define ID_VERSIONCONTROL_CHECKIN33271  33276
#define ID_SECONDARY_PROPERTIES         33277
#define ID_MANIFEST_PROPERTIES          33278
#define ID_PRIMARY_REMOVE               33279
#define ID_MANIFEST_REMOVE              33280
#define ID_COLLAPSEALL_ALL              33281
#define ID_COLLAPSEALL_ALL33277         33282
#define ID_COLLAPSE_SELECTION           33283
#define ID_COLLAPSE_ALL                 33284
#define ID_INSTANCES_COLLAPSESELECTION  33285
#define ID_TOOLS_HEATMAP                33286
#define ID_Menu33287                    33287
#define ID_FILE_VERSIONCONTROL          33288
#define ID_Menu33289                    33289
#define ID_VERSIONCONTROL_ADD           33290
#define ID_VERSIONCONTROL_CHECKOUT33291 33291
#define ID_VERSIONCONTROL_CHECKIN33292  33292
#define ID_VERSIONCONTROL_OVERVIEW      33293
#define ID_FILE_VERSIONCONTROL_CHECKOUT33291 33294
#define ID_FILE_VERSIONCONTROL_CHECKOUT 33295
#define ID_FILE_VERSIONCONTROL_ADD      33296
#define ID_FILE_VERSIONCONTROL_CHECKIN  33297
#define ID_FILE_VERSIONCONTROL_OVERVIEW 33298
#define ID_VERSIONCONTROL_CHECKINALL33299 33299
#define ID_FILE_VERSIONCONTROL_CHECKINALL 33300
#define ID_VERSIONCONTROL_CHECKOUTMANIFEST 33302
#define ID_VERSIONCONTROL_ADDMANIFEST   33303
#define ID_TOOLS_SPRINKLE               33304
#define ID_ACCELERATOR33293             33305
#define ID_VIEW_PREVIEWGRIDNAV          33306
#define ID_BLEND_SELECT_TEXTURE_1       33307
#define ID_BLEND_SHRINK_BRUSH           33308
#define ID_BLEND_SELECT_TEXTURE_2       33309
#define ID_BLEND_SELECT_TEXTURE_3       33310
#define ID_BLEND_SELECT_TEXTURE_4       33311
#define ID_BLEND_ENLARGE_BRUSH          33313
#define ID_VIEW_QUICKHIDE               33314
#define ID_VIEW_QUICKHIDEUNSELECTED     33315
#define ID_VIEW_QUICKUNHIDE             33316
#define ID_FILE_VERSIONCONTROL_CHECKOUTBSP 33318
#define ID_TOGGLE_RADIUSCULLING         33319
#define ID_VIEW_QUICKHIDEVISGROUP       33320
#define ID_INSTANCES_COLLAPSESELECTIONRECURSIVE 33321
#define ID_INSTANCES_COLLAPSEALLRECURSIVE 33322
#define IDS_NOPLAYERSTART               40000
#define IDS_MIXEDFACES                  40001
#define IDS_DUPLICATEPLANES             40002
#define IDS_UNMATCHEDTARGET             40003
#define IDS_INVALIDTEXTURE              40004
#define IDS_SOLIDSTRUCTURE              40005
#define IDS_UNUSEDKEYVALUES             40006
#define IDS_EMPTYENTITY                 40007
#define IDS_DUPLICATEKEYS               40008
#define IDS_SOLIDCONTENT                40009
#define IDS_INVALIDTEXTUREAXES          40010
#define IDS_INVALIDLIGHTMAPSIZEONDISP   40011
#define IDS_DUPLICATEFACEID             40012
#define IDS_DUPLICATE_NODE_ID           40013
#define IDS_BAD_CONNECTIONS             40014
#define IDS_HIDDEN_GROUP_HIDDEN_CHILDREN 40015
#define IDS_HIDDEN_GROUP_VISIBLE_CHILDREN 40016
#define IDS_HIDDEN_GROUP_MIXED_CHILDREN 40017
#define IDS_HIDDEN_NO_VISGROUP          40018
#define IDS_HIDDEN_CHILD_OF_ENTITY      40019
#define IDS_HIDDEN_ILLEGALLY            40020
#define IDS_KILL_INPUT_RACE_CONDITION   40021
#define IDS_BAD_OVERLAY                 40022
#define IDS_NOPLAYERSTART_DESC          40500
#define IDS_MIXEDFACES_DESC             40501
#define IDS_DUPLICATEPLANES_DESC        40502
#define IDS_UNMATCHEDTARGET_DESC        40503
#define IDS_INVALIDTEXTURE_DESC         40504
#define IDS_SOLIDSTRUCTURE_DESC         40505
#define IDS_UNUSEDKEYVALUES_DESC        40506
#define IDS_EMPTYENTITY_DESC            40507
#define IDS_DUPLICATEKEYS_DESC          40508
#define IDS_SOLIDCONTENT_DESC           40509
#define IDS_INVALIDTEXTUREAXES_DESC     40510
#define IDS_INVALIDLIGHTMAPSIZEONDISP_DESC 40511
#define IDS_DUPLICATEFACEID_DESC        40512
#define IDS_DUPLICATE_NODE_ID_DESC      40513
#define IDS_BAD_CONNECTIONS_DESC        40514
#define IDS_HIDDEN_GROUP_HIDDEN_CHILDREN_DESC 40515
#define IDS_HIDDEN_GROUP_VISIBLE_CHILDREN_DESC 40516
#define IDS_HIDDEN_GROUP_MIXED_CHILDREN_DESC 40517
#define IDS_HIDDEN_NO_VISGROUP_DESC     40518
#define IDS_HIDDEN_CHILD_OF_ENTITY_DESC 40519
#define IDS_HIDDEN_ILLEGALLY_DESC       40520
#define IDS_KILL_INPUT_RACE_CONDITION_DESC 40521
#define IDS_DAB_OVERLAY_DESC            40522
#define IDS_LOADINGFILE                 41001
#define IDS_CREATINGMESH                41002
#define IDS_ERRLOADGRAPHIC              41003
#define IDS_NO_CONFIGS_AVAILABLE        41004
#define IDS_NO_TEXTURES_AVAILABLE       41005
#define ID_TOOLS_SYNC_MESH              41006
#define IDS_REFRESHING_SOUNDS           57667
#define ID_VIEW_FILTERCONTROL           0xE807
#define ID_VIEW_OBJECTBAR               0xE808
#define ID_VIEW_MAPTOOLSBAR             0xE809
#define ID_VIEW_MAPVIEWBAR              0xE80A
#define ID_VIEW_TEXTUREBAR              0xE80B
#define ID_VIEW_MAPOPSBAR               0xE80C
#define ID_VIEW_ANIMATIONBAR            0xE80D
#define ID_VIEW_DISPEDITTOOLBAR         0xE80E
#define ID_VIEW_SELECTION_MODE_BAR      0xE80F
#define ID_VIEW_MANIFEST_BAR            0xE811
#define ID_HDR                          0xf000
#define IDC_LPRVWINDOW                  0xf010

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        361
#define _APS_NEXT_COMMAND_VALUE         33323
#define _APS_NEXT_CONTROL_VALUE         1736
#define _APS_NEXT_SYMED_VALUE           117
#endif
#endif
