//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by hlfaceposer.rc
//
#define IDI_ICON1                       101
#define IDD_ACTORPROPERTIES             102
#define IDD_INPUTDIALOG                 103
#define IDD_EXPRESSIONPROPERTIES        104
#define IDI_WORKSPACE                   104
#define IDD_CHANNELPROPERTIES           105
#define IDC_MOVETAG                     105
#define IDI_PROJECT                     105
#define IDD_EVENTPROPERTIES             106
#define IDI_SCENE                       106
#define IDD_PHONEMEPROPERTIES           107
#define IDI_VCD                         107
#define IDD_GLOBALEVENTPROPERTIES       108
#define IDI_WAV                         108
#define IDD_FLEXSLIDERS                 109
#define IDI_SPEAK                       109
#define IDI_GRAY                        112
#define IDI_UNCHECKED                   113
#define IDI_CHECKED                     114
#define IDD_CHOICEDIALOG                115
#define IDI_VCD_CHECKEDOUT              115
#define IDD_EDITPHRASE                  116
#define IDI_PROJECT_CHECKEDOUT          116
#define IDI_SPEAK_CHECKEDOUT            117
#define IDD_WAVELOOKUP                  118
#define IDI_WAV_CHECKEDOUT              118
#define IDD_ADDSOUNDENTRY               119
#define IDI_WORKSPACE_CHECKEDOUT        119
#define IDD_CCLOOKUP                    120
#define IDC_CURSOR1                     120
#define IDD_EVENTPROPERTIES_EXPRESSION  121
#define IDD_EVENTPROPERTIES_LOOKAT      122
#define IDD_EVENTPROPERTIES_MOVETO      123
#define IDD_EVENTPROPERTIES_SPEAK       124
#define IDD_EVENTPROPERTIES_GESTURE     125
#define IDD_EVENTPROPERTIES_SEQUENCE    126
#define IDD_EVENTPROPERTIES_FACE        127
#define IDD_EVENTPROPERTIES_FIRETRIGGER 128
#define IDD_EVENTPROPERTIES_FLEXANIMATION 129
#define IDD_EVENTPROPERTIES_SUBSCENE    130
#define IDD_EVENTPROPERTIES_INTERRUPT   131
#define IDD_EVENTPROPERTIES_STOPPOINT   132
#define IDD_EDGEPROPERTIES              132
#define IDD_EVENTPROPERTIES_PERMITRESPONSES 133
#define IDD_EVENTPROPERTIES_GENERIC     134
#define IDD_PROGRESS                    135
#define IDD_INPUTDIALOG1                136
#define IDD_MESSAGEBOX_WITHCHECKBOX     136
#define IDD_EVENTPROPERTIES_CAMERA      137
#define IDC_ACTORNAME                   1000
#define IDC_EXPRESSIONDESC              1001
#define IDC_STATIC_PROMPT               1003
#define IDC_EXPRESSIONNAME              1004
#define IDC_CHANNELNAME                 1005
#define IDC_EVENTCHOICES                1007
#define IDC_TYPENAME                    1008
#define IDC_SELECTWAV                   1009
#define IDC_EVENTCHOICES2               1010
#define IDC_FILENAME                    1011
#define IDC_TYPENAME2                   1011
#define IDC_EVENTCHOICES4               1011
#define IDC_EVENTNAME                   1012
#define IDC_ACTORCHOICE                 1013
#define IDC_CHOICES2PROMPT              1013
#define IDC_STATIC_ACTOR                1014
#define IDC_CHOICES3PROMPT              1014
#define IDC_STARTTIME                   1015
#define IDC_ENDTIME                     1016
#define IDC_LOOPTIME                    1016
#define IDC_CHECK_ENDTIME               1017
#define IDC_CHECK_RESUMECONDITION       1018
#define IDC_CHECK_AUTOCHECK             1019
#define IDC_CHECK_LOCKBODYFACING        1019
#define IDC_CB_AUTOACTION               1020
#define IDC_DURATION                    1021
#define IDC_INPUTSTRING                 1022
#define IDC_LOOPCOUNT                   1023
#define IDC_PHONEMENAME                 1024
#define IDC_ABSOLUTESTART               1025
#define IDC_RELATIVESTART               1026
#define IDC_TAGS                        1027
#define IDC_EDIT_PHONEME                1028
#define IDC_PHONEMETEXTPROMPT           1029
#define IDC_STATIC_HELPTEXT             1030
#define IDC_STATIC_SPLINE               1038
#define IDC_SLIDERS                     1040
#define IDC_CHOICE                      1043
#define IDC_EVENTCHOICES3               1044
#define IDC_STATIC_PITCH                1046
#define IDC_STATIC_YAW                  1047
#define IDC_SLIDER_PITCH                1048
#define IDC_SLIDER_YAW                  1049
#define IDC_STATIC_PITCHVAL             1050
#define IDC_STATIC_YAWVAL               1051
#define IDC_CHECK_LOOKAT                1052
#define IDC_STATIC_LOOPCOUNT            1054
#define IDC_STATIC_LOOPTIME             1055
#define IDC_STATIC_AFTER                1056
#define IDC_STATIC_SECONDS              1057
#define IDC_SHOW_ALL_SOUNDS             1058
#define IDC_SOUNDENTRYLIST              1059
#define IDC_CAPTION_ATTENUATION         1059
#define IDC_ADDENTRY                    1061
#define IDC_SOUNDNAME                   1061
#define IDC_SOUNDSCRIPT                 1062
#define IDC_CCTOKEN                     1065
#define IDC_CCTOKENLIST                 1066
#define IDC_SOUNDLIST                   1067
#define IDC_FILTER                      1068
#define IDC_STATIC_WAVEFILENAME         1069
#define IDC_STATIC_SCRIPTFILE           1070
#define IDC_PLAY_SOUND                  1071
#define IDC_OPENSOURCE                  1072
#define IDC_STATIC_DISTANCE             1074
#define IDC_SLIDER_DISTANCE             1075
#define IDC_STATIC_DISTANCEVAL          1076
#define IDC_LEFT_CURVETYPE              1077
#define IDC_RIGHT_CURVETYPE             1078
#define IDC_LEFT_ACTIVE                 1079
#define IDC_RIGHT_ACTIVE                1080
#define IDC_LEFT_ZEROVALUE              1081
#define IDC_RIGHT_ZEROVALUE             1082
#define IDC_LEFT_RESET                  1083
#define IDC_RIGHT_RESET                 1084
#define IDC_CHECK1                      1086
#define IDC_HOLD_OUT                    1086
#define IDC_MESSAGEBOX_CHECKBOX         1086
#define IDC_CHECK_FORCESHORTMOVEMENT    1087
#define IDC_CHECK_SYNCTOFOLLOWINGGESTURE 1088
#define IDC_CHECK_DISABLED              1090
#define IDC_CHECK_PLAYOVERSCRIPT        1091
#define IDC_FP_PROGRESS                 1092
#define IDC_FP_PROGRESS_TITLE           1093
#define IDC_FP_PROGRESS_TEXT            1094
#define IDC_FP_PROGRESS_CANCEL          1095
#define IDC_FP_PROGRESS_PERCENT         1095
#define IDC_FP_PROGRESS_ETA             1096

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        133
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1096
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
