#define IDD_BUTTONS                 100
#define IDC_CURSORS                 101
#define IDC_NAMES                   102
#define IDC_LOGICAL                 103
#define IDC_MOUSE                   104
#define IDC_PEN                     105
#define IDC_DEFAULT                 106

#define IDD_BTNMASKS				600
#define BMD_BASE					601
#define BMD_MAX						632
#define BMD_DISPLAY					665
#define BMU_BASE					633
#define BMU_MAX						664
#define BMU_DISPLAY					668
#define XBD_DISPLAY1                669
#define XBD_DISPLAY2                670
#define XBD_DISPLAY3                671
#define XBD_DISPLAY4                672
#define XBD_DISPLAY5                673
#define XBD_DISPLAY6                674
#define XBD_DISPLAY7                675
#define XBD_DISPLAY8                676
#define XBU_DISPLAY1                677
#define XBU_DISPLAY2                678
#define XBU_DISPLAY3                679
#define XBU_DISPLAY4                680
#define XBU_DISPLAY5                681
#define XBU_DISPLAY6                682
#define XBU_DISPLAY7                683
#define XBU_DISPLAY8                684
